/**
 * claude-embed.mjs — the installer's CLAUDE.md rules block (BL-165, v3.6).
 *
 * Why: most projects do NOT wire `.claude/memory/` into the agent's context (no
 * autoMemoryDirectory, no hand-written pointer), so the corpus SMA builds is
 * invisible to the very agent it exists for. The installer therefore embeds ONE
 * managed block into the project's CLAUDE.md telling every future session where
 * the memory lives, how to load it, and how to coordinate — the same splice law
 * as `sma emit` (create / append / replace / unchanged / corrupt=refuse), under a
 * DIFFERENT anchor family (SMA:RULES) so the corpus block and the rules block
 * never fight over one span.
 *
 * Consume-never-reimplement (D-49.3-02): the splice engine is emit.mjs's
 * spliceBlock with injected markers — this module writes no second block law.
 * The inverse lives in deleteme.mjs (BLOCK_ANCHORS strips SMA:RULES too).
 *
 * Self-runnable: `node scripts/sma/lib/claude-embed.mjs --selftest` prints 1/0
 * as the last line (the P-BL-165 falsifiable check — safe-command allowlisted).
 */

import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spliceBlock } from './emit.mjs'

/** The SMA:RULES anchor family (md style only — CLAUDE.md is markdown). */
export const RULES_MARKERS = {
  beginPrefix: '<!-- SMA:RULES:BEGIN',
  end: '<!-- SMA:RULES:END -->',
}

/**
 * renderRulesBlock({version}) — the fixed block text (LF). Content law: SHORT
 * (~1.5 KiB), plain-English operating rules a coding agent needs to actually use
 * the installed framework; no marketing. Regenerated by the installer on every
 * init (a version bump replaces the block; user bytes outside are untouched).
 */
export function renderRulesBlock({ version = '' } = {}) {
  const v = version ? ` v${version}` : ''
  return [
    `<!-- SMA:RULES:BEGIN v1 sma-framework${v} — installed by \`npx sma-framework init\`; do not hand-edit inside this block (re-running init regenerates it; \`node scripts/sma/cli.mjs deleteme\` removes it) -->`,
    '',
    '## SMA — operating rules for agents in this project',
    '',
    'SMA is installed here: a layered memory + multi-terminal coordination framework.',
    'These rules make its state visible to you. All commands run from the repo root.',
    '',
    '- **Memory.** The project\'s learned lessons live in `.claude/memory/` as plain',
    '  markdown notes. Read `.claude/memory/MEMORY.md` (the generated index: an',
    '  always-relevant CORE plus a one-line-per-note index) at session start. Pull',
    '  topic notes on demand: `node scripts/sma/cli.mjs load --tags <a,b>`. Write a',
    '  new lesson as ONE flat `.md` file with frontmatter, then regenerate the index:',
    '  `node scripts/sma/cli.mjs build-index --write`.',
    '- **Coordination.** Other terminals may work on this checkout in parallel.',
    '  Before risky or broad edits run `node scripts/sma/cli.mjs status` (active',
    '  sessions, claims, collisions). Claim a scope you are about to change:',
    '  `node scripts/sma/cli.mjs claim <name> --globs "<glob>" --desc "<what>"`;',
    '  release it when done. Never ignore a collision warning silently.',
    '- **Shared counters.** A migration number or release version is allocated ONLY',
    '  via `node scripts/sma/cli.mjs next-slot migration|release` — never picked by',
    '  reading the last one.',
    '- **Receipts over prose.** A claim of "done" should carry a reproducible check',
    '  (`node scripts/sma/cli.mjs receipt-hash "<command>"`). `reverify` re-runs them.',
    '- **Economy ladder.** Before writing code ask, in order: does this need to exist?',
    '  already in this codebase? stdlib? native platform feature? installed dependency?',
    '  one line? Only then: the minimum that works. The floor is fixed — security,',
    '  data-loss handling, trust-boundary validation, and accessibility are',
    '  never on the chopping block.',
    '- **Entry points.** `/sma-start` (onboarding), `/sma-help` (command map),',
    '  `node scripts/sma/cli.mjs explain <topic>` (in-product explainers).',
    '- **Off-ramp.** `/sma-deleteme` removes the framework; the memory corpus stays.',
    '',
    RULES_MARKERS.end,
  ].join('\n')
}

/** The real io (installer + selftest); tests inject fakes. */
export const REAL_IO = {
  exists: (p) => existsSync(p),
  readFile: (p) => readFileSync(p, 'utf8'),
  writeFile: (p, text) => writeFileSync(p, text, 'utf8'),
}

/**
 * embedRules({projectDir, version, io}) — splice the rules block into
 * `<projectDir>/CLAUDE.md` under the managed-block law. Never throws: an fs error
 * reports `{action:'error'}` so the installer can warn and continue (an embed
 * failure must never fail an install).
 *
 * @returns {{action:'created'|'appended'|'replaced'|'unchanged'|'skipped-corrupt'|'error', path:string, detail?:string}}
 */
export function embedRules({ projectDir, version = '', io = REAL_IO } = {}) {
  const path = join(projectDir, 'CLAUDE.md')
  try {
    const existingText = io.exists(path) ? String(io.readFile(path)) : ''
    const block = renderRulesBlock({ version })
    const { text, action } = spliceBlock({ existingText, block, style: 'md', markers: RULES_MARKERS })
    if (action === 'created' || action === 'appended' || action === 'replaced') io.writeFile(path, text)
    return { action, path }
  } catch (err) {
    return { action: 'error', path, detail: String(err && err.message ? err.message : err) }
  }
}

/**
 * embedSelftest({tmpRoot}) — the P-BL-165 fixture round-trip on a real temp dir:
 *   1. fresh project           -> created; block present, memory rule named
 *   2. re-embed, same version  -> unchanged (idempotent, zero writes)
 *   3. user CLAUDE.md          -> appended; user bytes a byte-identical prefix
 *   4. version bump            -> replaced; user bytes still intact
 *   5. torn anchor pair        -> skipped-corrupt; file byte-identical
 * Returns 1 on full pass, else 0. Never throws.
 */
export function embedSelftest({ tmpRoot }) {
  try {
    // 1. fresh
    const fresh = join(tmpRoot, 'fresh')
    mkdirSync(fresh, { recursive: true })
    if (embedRules({ projectDir: fresh, version: '9.9.9' }).action !== 'created') return 0
    const created = readFileSync(join(fresh, 'CLAUDE.md'), 'utf8')
    if (!created.includes('SMA:RULES:BEGIN') || !created.includes('.claude/memory/MEMORY.md')) return 0
    // 49.4-07: the economy ladder ships WITH its safety carveout welded on — a ladder
    // line without the "never on the chopping block" floor scores 0 (CONS-49.4-07-B).
    if (!created.includes('Economy ladder') || !created.includes('never on the chopping block')) return 0

    // 2. idempotent
    if (embedRules({ projectDir: fresh, version: '9.9.9' }).action !== 'unchanged') return 0

    // 3. append preserves user bytes as a prefix
    const owned = join(tmpRoot, 'owned')
    mkdirSync(owned, { recursive: true })
    const userText = '# My rules\n\nDo not touch my prose.\n'
    writeFileSync(join(owned, 'CLAUDE.md'), userText, 'utf8')
    if (embedRules({ projectDir: owned, version: '9.9.9' }).action !== 'appended') return 0
    const appended = readFileSync(join(owned, 'CLAUDE.md'), 'utf8')
    if (!appended.startsWith(userText)) return 0

    // 4. version bump replaces ONLY the span
    if (embedRules({ projectDir: owned, version: '10.0.0' }).action !== 'replaced') return 0
    const replaced = readFileSync(join(owned, 'CLAUDE.md'), 'utf8')
    if (!replaced.startsWith(userText) || !replaced.includes('v10.0.0')) return 0

    // 5. torn pair refused, file untouched
    const corrupt = join(tmpRoot, 'corrupt')
    mkdirSync(corrupt, { recursive: true })
    const torn = '<!-- SMA:RULES:BEGIN v1 -->\nno end line\n'
    writeFileSync(join(corrupt, 'CLAUDE.md'), torn, 'utf8')
    if (embedRules({ projectDir: corrupt, version: '9.9.9' }).action !== 'skipped-corrupt') return 0
    if (readFileSync(join(corrupt, 'CLAUDE.md'), 'utf8') !== torn) return 0

    return 1
  } catch {
    return 0
  }
}

// ── direct-run selftest (`node scripts/sma/lib/claude-embed.mjs --selftest`) ──
const invokedDirectly = (() => {
  try {
    return Boolean(process.argv[1]) && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))
  } catch {
    return false
  }
})()
if (invokedDirectly && process.argv.includes('--selftest')) {
  const { mkdtempSync } = await import('node:fs')
  const { tmpdir } = await import('node:os')
  const tmpRoot = mkdtempSync(join(tmpdir(), 'sma-embed-'))
  let ok = 0
  try {
    ok = embedSelftest({ tmpRoot })
  } finally {
    try {
      rmSync(tmpRoot, { recursive: true, force: true, maxRetries: 3 })
    } catch {
      /* best-effort cleanup */
    }
  }
  process.stdout.write(`${ok}\n`)
  process.exit(ok === 1 ? 0 : 1)
}
