/**
 * emit.mjs — `sma emit`: one corpus, any agent (Phase 49.3 Plan 04, D-49.3-08).
 *
 * Compiles the learned memory corpus into a MANAGED EXPORT BLOCK inside each of
 * CLAUDE.md / AGENTS.md / .cursorrules / GEMINI.md, every block under a per-format
 * byte budget. The block is regenerated from the corpus, never hand-edited in
 * place: portability = anti-lock-in, value even for non-Claude-Code users.
 *
 * DETERMINISM CONTRACT (inherited verbatim from generator.mjs, T-49-09-01):
 *   - commitHash + dateMap are ARGUMENTS, never read from the environment here.
 *     No clock, no mtime, no HEAD read in the output-producing path.
 *   - Ordering is the ONE shared truth: makeComparator (importance desc -> injected
 *     dateMap date desc -> name asc). emit re-derives NOTHING — it imports the
 *     comparator MEMORY.md and the loader already share.
 *   - LF line endings, UTF-8 no BOM.
 *
 * MANAGED-BLOCK LAW (D-49.3-08, T-49.3-04-A): spliceBlock only ever replaces the
 * BEGIN..END span; a file without a block gets it appended (every pre-existing
 * byte unchanged); an absent file is created holding only the block; a file whose
 * anchor pair is broken is NEVER written (skipped-corrupt, file untouched). The
 * ruler tool's documented clobbering failure is the named anti-lesson.
 *
 * INJECTION DEFENSE (T-49.3-04-B): note content is never executed; every
 * note-derived field is newline-collapsed to a single line and the anchor token
 * is defanged (colon-form SMA:EXPORT: -> dash-form SMA-EXPORT-) before rendering,
 * so no injected line can ever open or close a managed block.
 *
 * emit performs git READ ops only (hash + dateMap arrive injected) and NEVER
 * commits or pushes — output lands as a reviewable working-tree diff (T-49.3-03).
 *
 * Corpus access is ONLY through frontmatter.mjs (parseNote) — the single shared
 * read path (49-04). Node built-ins only; zero npm deps, no LLM, no network.
 */

import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { Buffer } from 'node:buffer'

import { parseNote } from './frontmatter.mjs'
import { makeComparator } from './generator.mjs'
import { atomicWriteRaw } from './fs-atomics.mjs'
import { EMIT_BUDGETS } from './constants.mjs'

// ─────────────────────────── format registry ─────────────────────────────────

/**
 * EMIT_FORMATS — the four target instruction files and their anchor style.
 * style 'md' -> HTML-comment anchors (CLAUDE.md / AGENTS.md / GEMINI.md);
 * style 'txt' -> `# >>> ` / `# <<< ` line anchors (.cursorrules — plain text).
 */
export const EMIT_FORMATS = [
  { id: 'claude', file: 'CLAUDE.md', style: 'md' },
  { id: 'agents', file: 'AGENTS.md', style: 'md' },
  { id: 'cursorrules', file: '.cursorrules', style: 'txt' },
  { id: 'gemini', file: 'GEMINI.md', style: 'md' },
]

/** Kinds that must never fossilize into a standing instruction file. */
const EXCLUDED_KINDS = new Set(['status', 'episodic'])

/** Structural corpus files that are not notes (mirror of generator.mjs). */
const STRUCTURAL_FILES = new Set(['MEMORY.md', 'ARCHIVE.md', 'TAGS.md'])
function isStructuralFile(f) {
  return STRUCTURAL_FILES.has(f) || /^INDEX-[^/\\]+\.md$/.test(f)
}

/** The colon-form anchor token, and its defanged dash-form replacement. */
const ANCHOR_TOKEN = 'SMA:EXPORT:'
const ANCHOR_TOKEN_DEFANGED = 'SMA-EXPORT-'

// ─────────────────────────── anchors ─────────────────────────────────────────

/** The regenerate-instead warning carried in every BEGIN anchor. */
const BEGIN_WARNING = 'generated by `pnpm sma emit`; do not hand-edit inside this block; regenerate instead'

/**
 * makeAnchors({style, file, commitHash}) — the whole-line BEGIN/END markers.
 * The commit hash is a full 40-hex (constant width -> stable byte math); `v1` is
 * the block-format version for forward migration. The BEGIN prefix (without the
 * hash) is what spliceBlock matches on a whole-line basis.
 *
 * @returns {{begin:string, end:string, beginPrefix:string}}
 */
export function makeAnchors({ style, file, commitHash }) {
  const hash = String(commitHash ?? '0'.repeat(40))
  if (style === 'txt') {
    return {
      beginPrefix: '# >>> SMA:EXPORT:BEGIN',
      begin: `# >>> SMA:EXPORT:BEGIN v1 fmt=${file} commit=${hash} ${BEGIN_WARNING}`,
      end: '# <<< SMA:EXPORT:END',
    }
  }
  return {
    beginPrefix: '<!-- SMA:EXPORT:BEGIN',
    begin: `<!-- SMA:EXPORT:BEGIN v1 fmt=${file} commit=${hash} ${BEGIN_WARNING} -->`,
    end: '<!-- SMA:EXPORT:END -->',
  }
}

/** The style's whole-line anchor markers WITHOUT the commit hash (splice/parse). */
export function anchorMarkers(style) {
  if (style === 'txt') return { beginPrefix: '# >>> SMA:EXPORT:BEGIN', end: '# <<< SMA:EXPORT:END' }
  return { beginPrefix: '<!-- SMA:EXPORT:BEGIN', end: '<!-- SMA:EXPORT:END -->' }
}

// ─────────────────────────── sanitization ────────────────────────────────────

/**
 * sanitize(s) — make a note-derived field safe to render on ONE block line:
 * collapse every CR/LF run to a single space (single-line entries mean no injected
 * line can start with an anchor), then defang the anchor token so a note body that
 * embeds `SMA:EXPORT:BEGIN/END` can never open or close the managed block.
 */
function sanitize(s) {
  return String(s ?? '')
    .replace(/[\r\n]+/g, ' ')
    .split(ANCHOR_TOKEN)
    .join(ANCHOR_TOKEN_DEFANGED)
    .trim()
}

// ─────────────────────────── corpus read + eligibility ───────────────────────

/** List note files (*.md, non-structural), sorted — the same filter as generator.mjs. */
function listNoteFiles(corpusDir) {
  let entries
  try {
    entries = readdirSync(corpusDir)
  } catch {
    return []
  }
  return entries
    .filter((f) => f.endsWith('.md') && !isStructuralFile(f))
    .filter((f) => {
      try {
        return statSync(join(corpusDir, f)).isFile()
      } catch {
        return false
      }
    })
    .sort()
}

/**
 * collectEligible(corpusDir) — parse every note via the single read path and split
 * into eligible records + per-reason exclusion counts. Eligibility gate (light,
 * "linted corpus only"): kind not in {status, episodic}, a non-empty description,
 * and a numeric importance. A parse failure is fail-soft skipped and counted.
 *
 * @returns {{eligible:object[], excluded:Record<string,number>}}
 */
function collectEligible(corpusDir) {
  const eligible = []
  const excluded = { 'kind-excluded': 0, 'no-description': 0, 'no-importance': 0, 'parse-error': 0 }

  for (const file of listNoteFiles(corpusDir)) {
    let text
    try {
      text = readFileSync(join(corpusDir, file), 'utf8')
    } catch {
      excluded['parse-error']++
      continue
    }
    let fm
    try {
      fm = parseNote(text, { file }).frontmatter
    } catch {
      excluded['parse-error']++
      continue
    }
    if (fm == null) {
      excluded['parse-error']++
      continue
    }

    const kind = String(fm.kind ?? '').trim()
    if (EXCLUDED_KINDS.has(kind)) {
      excluded['kind-excluded']++
      continue
    }
    const description = typeof fm.description === 'string' ? fm.description.trim() : ''
    if (description === '') {
      excluded['no-description']++
      continue
    }
    const importance = fm.importance
    if (importance == null || !Number.isFinite(Number(importance))) {
      excluded['no-importance']++
      continue
    }

    eligible.push({
      file,
      name: file.replace(/\.md$/, ''),
      kind,
      description,
      useWhen: typeof fm['use-when'] === 'string' ? fm['use-when'].trim() : '',
      importance: Number(importance),
    })
  }

  return { eligible, excluded }
}

// ─────────────────────────── entry + scaffold rendering ──────────────────────

/**
 * renderEntry(note, style) — ONE block line for a note, all fields sanitized.
 * md: `- **{name}** ({kind}, imp {importance}): {description}` + optional use-when.
 * txt: same minus the bold markers.
 */
function renderEntry(note, style) {
  const name = sanitize(note.name)
  const kind = sanitize(note.kind)
  const imp = sanitize(note.importance)
  const desc = sanitize(note.description)
  const useWhen = note.useWhen ? sanitize(note.useWhen) : ''
  const label = style === 'txt' ? name : `**${name}**`
  const tail = useWhen ? ` [use-when: ${useWhen}]` : ''
  return `- ${label} (${kind}, imp ${imp}): ${desc}${tail}`
}

/** The 2-line preamble (what this block is; source; regenerate command). */
function renderPreamble(corpusDir) {
  return [
    'SMA learned-corpus export — machine-generated. Do not hand-edit inside this block.',
    `Source corpus: ${corpusDir}. Regenerate with: pnpm sma emit`,
  ]
}

/** The footer line: how many of the eligible notes made the budget cut. */
function renderFooter(k, m, corpusDir) {
  return `${k} of ${m} eligible notes exported; full corpus: ${corpusDir} (pnpm sma load)`
}

/**
 * blockLines — the canonical line array of a managed block. selectNotes (scaffold
 * sizing) and renderBlock (final render) BOTH go through this so the byte math can
 * never drift from the artifact.
 */
function blockLines({ anchors, preamble, entryLines, footer }) {
  return [anchors.begin, '', ...preamble, '', ...entryLines, footer, anchors.end]
}

// ─────────────────────────── selection (deterministic, budgeted) ─────────────

/**
 * selectNotes({corpusDir, dateMap, budgetBytes, style, commitHash, file}) —
 * eligibility gate + shared-comparator order + strict priority-prefix fill.
 *
 * Scaffold bytes (anchors + preamble + WIDEST footer, k=m) are reserved first,
 * then entries are added in priority order until the next one would overflow the
 * budget — iteration STOPS at the first overflow, no backfill (T3). The widest
 * footer reservation means late footer substitution can never overflow (T4).
 *
 * @returns {{included:object[], excluded:Record<string,number>, totalEligible:number}}
 */
export function selectNotes({ corpusDir, dateMap = {}, budgetBytes, style, commitHash, file }) {
  const { eligible, excluded } = collectEligible(corpusDir)
  eligible.sort(makeComparator(dateMap))
  const m = eligible.length

  const anchors = makeAnchors({ style, file, commitHash })
  const preamble = renderPreamble(corpusDir)
  const widestFooter = renderFooter(m, m, corpusDir)

  // Scaffold = the block with ZERO entries and the widest possible footer.
  const scaffold = blockLines({ anchors, preamble, entryLines: [], footer: widestFooter }).join('\n')
  let curBytes = Buffer.byteLength(scaffold, 'utf8')

  const included = []
  for (const note of eligible) {
    const entryLine = renderEntry(note, style)
    // Adding one entry inserts `entryLine` + one `\n` separator into the join.
    const addBytes = Buffer.byteLength(entryLine, 'utf8') + 1
    if (curBytes + addBytes > budgetBytes) break // strict prefix — stop at first overflow
    included.push(note)
    curBytes += addBytes
  }

  return { included, excluded, totalEligible: m }
}

/**
 * renderBlock({format, selection, commitHash, corpusDir}) — the final managed-block
 * text (LF, no BOM). The actual footer (k <= m) is <= the widest footer reserved in
 * selectNotes, so the rendered block is guaranteed within budget.
 */
export function renderBlock({ format, selection, commitHash, corpusDir }) {
  const anchors = makeAnchors({ style: format.style, file: format.file, commitHash })
  const preamble = renderPreamble(corpusDir)
  const entryLines = selection.included.map((n) => renderEntry(n, format.style))
  const footer = renderFooter(selection.included.length, selection.totalEligible, corpusDir)
  return blockLines({ anchors, preamble, entryLines, footer }).join('\n')
}

// ─────────────────────────── splice engine (the managed-block law) ───────────

/**
 * locateBlock(text, style) — find the managed block by WHOLE-LINE anchor match: a
 * line starting with the style's BEGIN prefix, and the style's exact END line.
 * Returns the classification the splice/check paths both share.
 *
 * @returns {{status:'none'|'ok'|'corrupt', begin?:number, end?:number}}
 */
function locateBlock(text, style) {
  const { beginPrefix, end: endLine } = anchorMarkers(style)
  const lines = String(text ?? '').split('\n')
  const begins = []
  const ends = []
  lines.forEach((l, i) => {
    if (l.startsWith(beginPrefix)) begins.push(i)
    if (l === endLine) ends.push(i)
  })
  if (begins.length === 0 && ends.length === 0) return { status: 'none' }
  // Exactly one BEGIN, one END, END at/after BEGIN — anything else is corrupt
  // (BEGIN without END, END before BEGIN, duplicate BEGIN/END). Never written.
  if (begins.length !== 1 || ends.length !== 1 || ends[0] < begins[0]) return { status: 'corrupt' }
  return { status: 'ok', begin: begins[0], end: ends[0] }
}

/**
 * spliceBlock({existingText, block, style}) — PURE (no fs). The managed-block law:
 *   - empty existing text            -> {created}   block + one trailing LF
 *   - present, no block              -> {appended}  userContent (byte-identical
 *                                        prefix) + exactly one blank line + block + LF
 *   - present, one clean block       -> {replaced}  only the BEGIN..END span changes
 *   - spliced result equals input    -> {unchanged} (idempotence)
 *   - corrupt anchor pair            -> {skipped-corrupt} text returned untouched
 *
 * @returns {{text:string, action:'created'|'appended'|'replaced'|'unchanged'|'skipped-corrupt'}}
 */
export function spliceBlock({ existingText, block, style }) {
  const text = String(existingText ?? '')
  const loc = locateBlock(text, style)

  if (loc.status === 'corrupt') return { text, action: 'skipped-corrupt' }

  if (loc.status === 'none') {
    if (text === '') return { text: block + '\n', action: 'created' }
    // Append non-destructively: user content is ALWAYS a byte-identical prefix,
    // with exactly one blank line before the block.
    const sep = text.endsWith('\n\n') ? '' : text.endsWith('\n') ? '\n' : '\n\n'
    return { text: `${text}${sep}${block}\n`, action: 'appended' }
  }

  // status 'ok' — replace exactly the BEGIN..END span, leave head + tail untouched.
  const lines = text.split('\n')
  const head = lines.slice(0, loc.begin)
  const tail = lines.slice(loc.end + 1)
  const newText = [...head, ...block.split('\n'), ...tail].join('\n')
  if (newText === text) return { text, action: 'unchanged' }
  return { text: newText, action: 'replaced' }
}

// ─────────────────────────── emitAll (write + --check) ───────────────────────

/** The default fs-atomics-backed io — every write goes through atomicWriteRaw. */
const DEFAULT_IO = {
  exists: (p) => existsSync(p),
  readFile: (p) => readFileSync(p, 'utf8'),
  writeFileAtomic: (p, text) => atomicWriteRaw(p, text),
}

/** Map declared agent-tool facts to emit format ids (forward-compat, fail-soft). */
const TOOL_TO_FORMAT = {
  claude: 'claude',
  'claude-code': 'claude',
  codex: 'agents',
  openai: 'agents',
  agents: 'agents',
  cursor: 'cursorrules',
  gemini: 'gemini',
}

/**
 * resolveFormats({formats, profilePath, io}) — the caller's explicit formats win.
 * With none passed, consult the 49.3-01 onboarding profile (SCORECARD METRIC 5:
 * this read is the live consumption that keeps a declared agent-tools field alive
 * under the dead-field lint) and narrow/order the default set; on ANY failure
 * (absent, unreadable, field missing) fall back to all four formats SILENTLY.
 * NOTE: profile schema v2 (49.3-01) ships NO agent-tools field, so today this
 * ALWAYS fails soft to all four — the permanent default until such a field lands.
 */
function resolveFormats({ formats, profilePath, io }) {
  if (Array.isArray(formats) && formats.length) return formats
  try {
    if (profilePath) {
      const prof = JSON.parse(io.readFile(profilePath))
      const declared = prof.agentTools ?? prof['agent-tools']
      if (Array.isArray(declared) && declared.length) {
        const ids = declared.map((t) => TOOL_TO_FORMAT[String(t).trim().toLowerCase()]).filter(Boolean)
        const chosen = EMIT_FORMATS.filter((f) => ids.includes(f.id))
        if (chosen.length) return chosen
      }
    }
  } catch {
    /* fail-soft — all four formats */
  }
  return EMIT_FORMATS
}

/** Parse the commit hash out of an existing block's BEGIN anchor line. */
function parseAnchorHash(text, style) {
  const { beginPrefix } = anchorMarkers(style)
  for (const line of String(text ?? '').split('\n')) {
    if (line.startsWith(beginPrefix)) {
      const m = /commit=([0-9a-f]{40})/.exec(line)
      return m ? m[1] : null
    }
  }
  return null
}

/**
 * emitAll(opts) — run every format: selectNotes + renderBlock + spliceBlock.
 *
 * Write mode: atomic writes only for created/appended/replaced (unchanged +
 * skipped-corrupt write NOTHING). Check mode writes NOTHING and classifies each
 * format into exactly ONE count — priority missing > corrupt > overBudget > drift:
 *   - absent file                     -> missing (never drift)
 *   - no block / corrupt / bad hash   -> corrupt (torn pair; a regression, not auto-fixed)
 *   - regen block over budget         -> overBudget
 *   - existing block != regen@anchor  -> drift (regen uses the hash PARSED FROM the
 *                                        artifact's own anchor — MEM-REGEN posture, so a
 *                                        moved HEAD alone is never drift)
 *
 * commitHash + dateMap arrive as ARGUMENTS — no git, no clock in this module.
 *
 * @returns {{results:object[], counts:{drift:number, overBudget:number, corrupt:number, missing:number}}}
 */
export function emitAll(opts) {
  const {
    targetDir,
    corpusDir,
    tagsPath,
    commitHash,
    dateMap = {},
    budgets = {},
    formats,
    check = false,
    io = DEFAULT_IO,
    profilePath,
  } = opts

  const formatList = resolveFormats({ formats, profilePath, io })
  const counts = { drift: 0, overBudget: 0, corrupt: 0, missing: 0 }
  const results = []

  for (const fmt of formatList) {
    const budget = budgets[fmt.id] ?? EMIT_BUDGETS[fmt.id] ?? EMIT_BUDGETS.claude
    const targetPath = join(targetDir, fmt.file)
    const exists = io.exists(targetPath)
    const existingText = exists ? io.readFile(targetPath) : ''

    if (check) {
      // Regenerate at the hash PARSED FROM the artifact's own anchor (MEM-REGEN).
      const anchorHash = exists ? parseAnchorHash(existingText, fmt.style) : null
      const loc = exists ? locateBlock(existingText, fmt.style) : { status: 'none' }

      let status
      if (!exists) {
        status = 'missing'
        counts.missing++
      } else if (loc.status === 'none') {
        // file present but carries no managed block — the block is missing
        status = 'missing'
        counts.missing++
      } else if (loc.status === 'corrupt' || anchorHash == null) {
        status = 'corrupt'
        counts.corrupt++
      } else {
        const sel = selectNotes({ corpusDir, tagsPath, dateMap, budgetBytes: budget, style: fmt.style, commitHash: anchorHash, file: fmt.file })
        const regen = renderBlock({ format: fmt, selection: sel, commitHash: anchorHash, corpusDir })
        const regenBytes = Buffer.byteLength(regen, 'utf8')
        const existingBlock = existingText.split('\n').slice(loc.begin, loc.end + 1).join('\n')
        if (regenBytes > budget) {
          status = 'over-budget'
          counts.overBudget++
        } else if (existingBlock !== regen) {
          status = 'drift'
          counts.drift++
        } else {
          status = 'clean'
        }
      }
      results.push({ file: fmt.file, action: status, budget })
      continue
    }

    // ── write mode ──
    const sel = selectNotes({ corpusDir, tagsPath, dateMap, budgetBytes: budget, style: fmt.style, commitHash, file: fmt.file })
    const block = renderBlock({ format: fmt, selection: sel, commitHash, corpusDir })
    const bytes = Buffer.byteLength(block, 'utf8')
    const spliced = spliceBlock({ existingText, block, style: fmt.style })
    if (spliced.action === 'skipped-corrupt') counts.corrupt++
    if (bytes > budget) counts.overBudget++
    if (spliced.action === 'created' || spliced.action === 'appended' || spliced.action === 'replaced') {
      io.writeFileAtomic(targetPath, spliced.text)
    }
    results.push({
      file: fmt.file,
      action: spliced.action,
      bytes,
      budget,
      included: sel.included.length,
      totalEligible: sel.totalEligible,
    })
  }

  return { results, counts }
}
