/**
 * generator.mjs — the R3 write engine of pillar 1's layered memory.
 *
 * Turns the memory corpus into MEMORY.md = an always-load CORE section (blockers,
 * current-task pointer, top facts) plus a sparse one-line-per-fact index (C1, B9,
 * B10). CORE is generated ONLY from memory notes — the repo instruction file is
 * NEVER an input (D-9-08). Output is byte-deterministic: no clock, no mtime, no HEAD
 * read in the output-producing path — the commit hash and the last-commit date map
 * are INJECTED so lint's MEM-REGEN (9-08) can byte-compare a committed artifact
 * against a fresh regeneration, and so the flip (9-14) can prove determinism.
 *
 * DETERMINISM CONTRACT (T-9-09-01):
 *   - commitHash + dateMap are arguments, never read from the environment here.
 *   - The single ordering comparator (importance desc → dateMap desc → name asc)
 *     is shared with the loader (9-09 loader.mjs imports orderNotes), so both the
 *     written index and the read-time query resolve ties the same way.
 *   - LF line endings, UTF-8 no BOM, sparse by threshold (B9 — no cataloguing).
 *
 * Exports (imported by lint 9-08 MEM-REGEN, flip 9-14):
 *   - GENERATED_MARKER : the single header line carrying 'GENERATED' + the build
 *     command name + a {commit} placeholder + the do-not-hand-edit warning.
 *   - buildIndex({corpusDir, tagsPath, commitHash, dateMap, coreThreshold}) → string
 *   - computeDateMap({execGit}) → {path: last-commit-ISO} from ONE git log pass
 *
 * TWO SCHEMA VERSIONS, ONE INDEX: the corpus may hold v1 notes and schema-v2
 * records side by side, and both are read through the same parser. Where the two
 * grammars name the same thing differently, this module maps them onto one axis
 * rather than growing a second rendering path:
 *   description ~ claim · kind ~ (memory_type, truth_mode) · tags ~ retrieval.areas ·
 *   importance≥threshold ~ context_priority: always.
 * On top of that sits ONE filter that outranks all of it: a record whose status
 * is superseded or revoked never reaches CORE (see CORE_EXCLUDED_STATUSES).
 *
 * EPISODES ARE INVISIBLE HERE BY CONSTRUCTION. `.claude/memory/episodes/` is a
 * subdirectory, and the corpus listing below is FLAT (readdirSync + isFile), so
 * no episode can reach the always-load payload even if someone forgets it
 * exists. That is asserted positively in the suite: adding an episode leaves the
 * generated bytes identical. Do not "fix" the listing into a recursive walk.
 *
 * Corpus access is ONLY through frontmatter.mjs (parseNote + loadTagsRegistry) —
 * the single shared read path (9-04). Node built-ins only; zero npm deps.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'

import { parseNote, loadTagsRegistry, resolveAlias } from './frontmatter.mjs'

/** Importance at/above which a note is CORE (always loaded). Sparse by design (B9). */
export const CORE_THRESHOLD = 9

/**
 * Lifecycle states that can NEVER reach always-load context, whatever else the
 * record says about itself. A superseded rule and a revoked one are not merely
 * less important — they are known to be wrong, and an index that keeps quoting
 * them into every session is worse than one that never learned them. They stay
 * catalogued in their area index (findable, with the state named) and out of CORE.
 */
export const CORE_EXCLUDED_STATUSES = new Set(['superseded', 'revoked'])

/**
 * The CORE membership question, asked ONCE for both schema versions:
 *   - a retired record is never CORE (the hard filter above);
 *   - a schema-v2 record states its own answer in `context_priority` — v2 has no
 *     `importance` field at all, so the threshold cannot speak for it;
 *   - everything else is the v1 law, unchanged: importance at/above threshold.
 *
 * Exported so a consumer sizing or trimming CORE asks the same question the
 * writer answered, instead of re-deriving membership from a field list.
 */
export function isCoreNote(n, coreThreshold = CORE_THRESHOLD) {
  if (CORE_EXCLUDED_STATUSES.has(n.status)) return false
  // A caller may raise the bar out of reach on purpose (`coreThreshold:
  // Infinity` — the reflex matcher's way of saying «there is no CORE here, route
  // every record through facet matching»). An unreachable bar means an EMPTY
  // core, so the v2 shortcut below must not smuggle records past it.
  if (!Number.isFinite(coreThreshold)) return n.importance >= coreThreshold
  if (n.contextPriority === 'always') return true
  if (n.contextPriority === 'on-demand') return false
  return n.importance >= coreThreshold
}

/**
 * GENERATED_MARKER — the exact header line lint MEM-REGEN greps to know the index
 * is a machine artifact. `{commit}` is substituted with the injected build hash.
 * A single HTML comment so it renders invisibly in the markdown index.
 */
export const GENERATED_MARKER =
  '<!-- GENERATED by scripts/sma memory index at commit {commit} — do not hand-edit; regenerate instead (машинный артефакт, не редактировать вручную) -->'

/** Structural files that are not notes — never fed to the generator. */
const STRUCTURAL_FILES = new Set(['MEMORY.md', 'ARCHIVE.md', 'TAGS.md'])

/** The FI-11 per-area index files are structural artifacts, never notes. */
function isStructuralFile(f) {
  return STRUCTURAL_FILES.has(f) || /^INDEX-[^/\\]+\.md$/.test(f)
}

/** The discovery-block fallback area for a note carrying no registered area tag. */
const MISC_AREA = 'misc'

/** Epoch fallback for a note with no dateMap entry (uncommitted → sorts last). */
const EPOCH = '0000-00-00T00:00:00Z'

/** kind subsection order inside CORE: active state first, then rules, then rest. */
const CORE_KIND_ORDER = ['status', 'procedural-rule', 'decision', 'reference', 'episodic', 'bug-lesson']

// ─────────────────────────── corpus read ─────────────────────────────────────

/** List note files (*.md, non-structural), sorted for a stable base order. */
function listNoteFiles(corpusDir) {
  let entries
  try {
    entries = readdirSync(corpusDir)
  } catch {
    return []
  }
  return entries
    .filter((f) => f.endsWith('.md') && !isStructuralFile(f))
    .filter((f) => {
      try {
        return statSync(join(corpusDir, f)).isFile()
      } catch {
        return false
      }
    })
    .sort()
}

/**
 * Read + parse every corpus note into a uniform record. A note whose frontmatter
 * fails to parse (or is missing) is skipped from the generated index — lint owns
 * schema errors (MEM-SCHEMA); the generator stays fail-soft (never crashes on a
 * bad note, so a regen during a partial migration still produces a stable file).
 *
 * Exported for trim.mjs (9.1-13): the trimmer sizes/demotes CORE through the
 * SAME read + render path the generator writes with — one membership truth.
 */
export function readNotes(corpusDir) {
  const notes = []
  for (const file of listNoteFiles(corpusDir)) {
    let text
    try {
      text = readFileSync(join(corpusDir, file), 'utf8')
    } catch {
      continue
    }
    let parsed
    try {
      parsed = parseNote(text, { file })
    } catch {
      continue
    }
    const fm = parsed.frontmatter
    if (fm == null) continue
    notes.push(projectNoteAxis(fm, { file, schemaVersion: parsed.schemaVersion }))
  }
  return notes
}

/**
 * projectNoteAxis(frontmatter, {file, schemaVersion}) — THE one-axis projection,
 * in ONE place.
 *
 * Every consumer that asks a corpus record "what is your claim / your kind / your
 * areas / are you always-load" goes through this function, so the two grammars
 * can never grow two answers. The mapping (also stated in the module header):
 *   description ~ claim · kind ~ (memory_type, truth_mode) · tags ~ retrieval.areas ·
 *   importance≥CORE_THRESHOLD ~ context_priority: always ·
 *   use-when ~ retrieval.hint · use-when-pattern ~ retrieval.paths[0] ·
 *   reflex ~ retrieval.reflex.
 *
 * The last pair is the migration's own inverse, not a new invention:
 * migrate-v1-v2.mjs writes `context_priority: importance >= 9 ? always : on-demand`,
 * so reading `always` back as CORE-eligible weight CORE_THRESHOLD round-trips a
 * migrated note to where it started. A v2 record carries no importance at all, so
 * an `on-demand` record weighs 0 and sorts at the tail — findable by facet, never
 * ahead of a note that states a number.
 *
 * Exported for loader.mjs (retrieval) and context-pack.mjs (pointer lines): the
 * read engine and the compiler read the SAME axis the index is written with.
 *
 * @param {object} fm  parsed frontmatter (v1 or v2)
 * @param {{file?:string, schemaVersion?:1|2}} [meta]
 * @returns {{file:string, description:string, kind:string, tags:string[], useWhen:string,
 *            importance:number, status:string, contextPriority:string, schemaVersion:1|2,
 *            weight:number, hint:string, pathPattern:string, reflexOptOut:boolean}}
 */
export function projectNoteAxis(fm, meta = {}) {
  const source = fm ?? {}
  const importance = Number(source.importance)
  const imp = Number.isFinite(importance) ? importance : 0
  const contextPriority = String(source.context_priority ?? '').trim()
  const retrieval = retrievalBlock(source)
  return {
    file: meta.file ?? '',
    // v1 says `description`, v2 says `claim` — one line about one fact, under
    // two names. Same slot in the rendered index either way.
    description: renderableText(source.description ?? source.claim),
    // v1 `kind` and v2 (memory_type, truth_mode) both answer "what sort of
    // knowledge is this" — see projectKind for the one collapsed pair.
    kind: projectKind(source),
    // v1 `tags` and v2 `retrieval.areas` are the SAME membership axis (1:1),
    // so the area grouping (and the loader's facet matching) needs no second path.
    tags: mergeAreas(source),
    useWhen: renderableText(source['use-when']),
    importance: imp,
    status: renderableText(source.status),
    contextPriority,
    schemaVersion: meta.schemaVersion ?? 1,
    // The ordering key. v2 carries no importance, so `always` is mapped onto
    // the same axis the comparator already sorts by — one chain, two grammars.
    weight: contextPriority === 'always' ? Math.max(imp, CORE_THRESHOLD) : imp,
    // ── trigger fields (read by the reflex consumer, never rendered) ──────
    // v1 `use-when` prose survives migration as `retrieval.hint`; the
    // `use-when-pattern` precision glob as `retrieval.paths[0]`; the per-note
    // opt-out `reflex: off` as `retrieval.reflex`. They sit here, beside the
    // rest of the axis, so no consumer has to learn the v2 grammar twice.
    hint: renderableText(source['use-when'] ?? retrieval.hint),
    pathPattern: renderableText(source['use-when-pattern'] ?? firstPath(retrieval)),
    reflexOptOut:
      renderableText(source.reflex ?? retrieval.reflex).toLowerCase() === 'off',
  }
}

/**
 * The v1 `kind` of a record, whichever grammar it is written in.
 *
 * v1 `kind` is a single word; v2 splits the same question across `memory_type`
 * (what sort of knowledge) and `truth_mode` (in what sense it is true). One v1
 * word collapsed onto a shared memory_type in that split — `bug-lesson` and
 * `procedural-rule` are BOTH `procedural` — so reading memory_type alone loses
 * the distinction that the corpus is asked for by name (the reflex consumer
 * asks for `bug-lesson`; nothing answers to `procedural`).
 *
 * The inverse is not a guess: migrate-v1-v2's KIND_TRANSFORM writes exactly
 * `bug-lesson -> procedural + factual` and `procedural-rule -> procedural +
 * normative`, so the pair reads back the word it came from. No new frontmatter
 * field, no data migration, one vocabulary. Every other memory_type is its own
 * answer and passes through untouched.
 */
const PROCEDURAL_BY_TRUTH_MODE = { factual: 'bug-lesson', normative: 'procedural-rule' }

function projectKind(fm) {
  const v1 = renderableText(fm.kind)
  if (v1) return v1
  const memoryType = renderableText(fm.memory_type)
  if (memoryType !== 'procedural') return memoryType
  const truthMode = renderableText(fm.truth_mode).toLowerCase()
  return PROCEDURAL_BY_TRUTH_MODE[truthMode] ?? memoryType
}

/** The v2 `retrieval` block as a plain object ({} when absent or malformed). */
function retrievalBlock(fm) {
  const r = fm.retrieval
  return r != null && typeof r === 'object' && !Array.isArray(r) ? r : {}
}

/** The first entry of `retrieval.paths` (the migrated precision glob), or ''. */
function firstPath(retrieval) {
  const raw = retrieval.paths
  if (Array.isArray(raw)) return raw.length ? raw[0] : ''
  return raw ?? ''
}

/** A frontmatter value as trimmed text; anything absent renders as empty. */
function renderableText(v) {
  return v == null ? '' : String(v).trim()
}

/** v1 tags plus any v2 retrieval.areas not already among them, order preserved. */
function mergeAreas(fm) {
  const tags = Array.isArray(fm.tags) ? fm.tags : []
  const retrieval = fm.retrieval
  if (retrieval == null || typeof retrieval !== 'object' || Array.isArray(retrieval)) return tags
  const raw = retrieval.areas
  const areas = (Array.isArray(raw) ? raw : raw == null ? [] : [raw])
    .map((a) => String(a).trim())
    .filter((a) => a !== '')
  if (areas.length === 0) return tags
  return tags.concat(areas.filter((a) => !tags.includes(a)))
}

// ─────────────────────────── ordering (single truth) ─────────────────────────

/**
 * makeComparator(dateMap) — the ONE ordering key shared by the generator and the
 * loader (9-09): importance desc → injected last-commit date desc → name asc.
 * Recency is NEVER the primary filter (R4). A missing dateMap entry sorts last.
 *
 * Exported so loader.mjs can import a single ordering truth (T-9-09-01).
 *
 * @param {Record<string,string>} dateMap  file → last-commit ISO
 * @returns {(a:{file:string,importance:number}, b:{file:string,importance:number})=>number}
 */
export function makeComparator(dateMap = {}) {
  return (a, b) => {
    // `weight` is importance for a v1 note and the context_priority mapping for
    // a v2 record; a caller that builds note objects without it (the loader's
    // own shape) keeps the exact v1 behaviour through the fallback.
    const ia = a.weight ?? a.importance
    const ib = b.weight ?? b.importance
    if (ib !== ia) return ib - ia
    const da = dateMap[a.file] ?? EPOCH
    const db = dateMap[b.file] ?? EPOCH
    if (db !== da) return db < da ? -1 : 1 // date desc
    return a.file < b.file ? -1 : a.file > b.file ? 1 : 0 // name asc
  }
}

// ─────────────────────────── rendering ───────────────────────────────────────

/**
 * Max chars of a description rendered into one line (memory-hygiene C1: one line
 * per fact, under ~200 chars — the detail lives in the note file the line links to).
 * MEMORY.md is always-loaded context; unbounded descriptions ballooned it past the
 * harness partial-load limit (2026-07-03: 64 KB, only partially loaded).
 */
const LINE_DESC_MAX = 200

/** Truncate at the cap on a whole word, marking the cut with an ellipsis. */
function truncateClaim(s) {
  if (s.length <= LINE_DESC_MAX) return s
  const cut = s.slice(0, LINE_DESC_MAX - 1)
  const atWord = cut.replace(/\s+\S*$/, '')
  return `${(atWord.length >= LINE_DESC_MAX / 2 ? atWord : cut).trimEnd()}…`
}

/** Letters/digits only, lowercased — the corpus's echo use-whens drop punctuation. */
function normalizeForEcho(s) {
  return s.toLowerCase().replace(/[^\p{L}\p{N}]/gu, '')
}

/**
 * The bulk-migrated corpus auto-filled use-when as 'при работе с: <first words of
 * the description>' — a pure echo that doubled almost every index line. Render only
 * a use-when that carries its own signal; a genuine trigger ('перед пушем', 'в
 * начале любой сессии') never matches the echo shape and is kept.
 */
function renderableUseWhen(n) {
  if (!n.useWhen) return ''
  const m = n.useWhen.match(/^при работе с:\s*(.*)$/iu)
  if (m == null) return truncateClaim(n.useWhen)
  const probe = normalizeForEcho(m[1])
  if (probe === '' || normalizeForEcho(n.description).startsWith(probe)) return ''
  return truncateClaim(n.useWhen)
}

/**
 * CORE line: a standalone claim + its use-when (agents read this every load).
 * The claim is a markdown link `[desc](file)` so the note path is a real link that
 * the lint MEM-ORPHAN parser (which recognizes `](name.md)`) sees — CORE notes are
 * part of the index, not orphans. Bold-wrapped so CORE still reads as emphasized.
 */
function renderCoreLine(n) {
  const useWhen = renderableUseWhen(n)
  return `- **[${truncateClaim(n.description)}](${n.file})**${useWhen ? ` — ${useWhen}` : ''}${statusSuffix(n)}`
}

/**
 * The lifecycle marker on a rendered line. A record that is not `active` is
 * still findable, and a reader must be able to see WHY it reads oddly without
 * opening it. A v1 note carries no `status` at all, so this is empty for the
 * entire pre-schema-v2 corpus — the generated bytes do not move.
 */
function statusSuffix(n) {
  return n.status && n.status !== 'active' ? ` · status: ${n.status}` : ''
}
// trim.mjs (9.1-13) sizes CORE demotions with the exact render the generator
// writes — exported so the byte math cannot drift from the artifact.
export { renderCoreLine }

/**
 * Index line (B10): a standalone claim + kind + tags + use-when + path, so an agent
 * judges relevance WITHOUT opening the file. One line per fact (C1).
 */
function renderIndexLine(n) {
  const tags = n.tags.join(', ')
  const useWhen = renderableUseWhen(n)
  return `- [${truncateClaim(n.description)}](${n.file}) · ${n.kind} · ${tags}${useWhen ? ` · ${useWhen}` : ''}${statusSuffix(n)}`
}

/** Order the CORE notes: kind subsection order, then the shared comparator within. */
function orderCore(coreNotes, cmp) {
  const rank = (k) => {
    const i = CORE_KIND_ORDER.indexOf(k)
    return i === -1 ? CORE_KIND_ORDER.length : i
  }
  return coreNotes.slice().sort((a, b) => {
    const ra = rank(a.kind)
    const rb = rank(b.kind)
    if (ra !== rb) return ra - rb
    return cmp(a, b)
  })
}

/**
 * buildIndex(opts) — render the whole MEMORY.md artifact deterministically.
 *
 * @param {object} opts
 * @param {string} opts.corpusDir      directory of the memory notes
 * @param {string} opts.tagsPath       path to TAGS.md (facet registry; parsed for stats)
 * @param {string} opts.commitHash     the build-anchor commit (INJECTED — never read here)
 * @param {Record<string,string>} [opts.dateMap]  file → last-commit ISO (INJECTED)
 * @param {number} [opts.coreThreshold]  importance at/above which a note is CORE
 * @returns {string}  the full generated MEMORY.md text (LF, no BOM)
 */
export function buildIndex(opts) {
  const {
    corpusDir,
    tagsPath,
    commitHash,
    dateMap = {},
    coreThreshold = CORE_THRESHOLD,
  } = opts

  const registry = loadTagsRegistry(tagsPath)

  const notes = readNotes(corpusDir)
  const cmp = makeComparator(dateMap)

  const core = orderCore(
    notes.filter((n) => isCoreNote(n, coreThreshold)),
    cmp,
  )
  // Everything CORE did not take — a demoted record is catalogued, never dropped.
  const periphery = notes.filter((n) => !isCoreNote(n, coreThreshold)).sort(cmp)
  const byArea = groupByArea(periphery, registry)

  const header = GENERATED_MARKER.replace('{commit}', commitHash ?? EPOCH)

  const out = []
  out.push(header)
  out.push('')
  out.push('# MEMORY — сгенерированный индекс памяти (R3)')
  out.push('')
  out.push(`> Построено из коммита \`${commitHash ?? EPOCH}\` · заметок: ${notes.length} · ядро: ${core.length} · индекс: ${periphery.length}.`)
  out.push('')

  // ── CORE (always loaded) ────────────────────────────────────────────────
  out.push('## Ядро (всегда загружается)')
  out.push('')
  if (core.length === 0) {
    out.push('_(пусто)_')
    out.push('')
  } else {
    for (const n of core) out.push(renderCoreLine(n))
    out.push('')
  }

  // ── Thin discovery layer (FI-11, 9.1-13) ───────────────────────────────
  // One line per AREA with a count; the full one-line-per-note catalog lives
  // in the per-area INDEX-<area>.md files, pulled by tag on demand via
  // `node scripts/sma/cli.mjs load` — always-load stays within its byte budget with zero loss
  // of discoverability.
  out.push('## Обзор областей (полные индексы по требованию — `node scripts/sma/cli.mjs load --tags <area>`)')
  out.push('')
  if (byArea.size === 0) {
    out.push('_(пусто)_')
    out.push('')
  } else {
    for (const area of [...byArea.keys()].sort()) {
      const count = byArea.get(area).length
      out.push(`- ${area} — заметок: ${count} → [INDEX-${area}.md](INDEX-${area}.md)`)
    }
    out.push('')
  }

  // LF endings, trailing newline, no BOM.
  return out.join('\n')
}

// ─────────────────────────── per-area index files (FI-11) ────────────────────

/**
 * A note's discovery areas: its alias-resolved tags that are registered area
 * facets. A note with several area tags is catalogued in EVERY matching area
 * index (discoverability beats deduplication for a catalog); a note with no
 * registered area tag lands in the `misc` bucket so nothing is uncatalogued.
 */
function noteAreas(n, registry) {
  const resolved = (n.tags ?? []).map((t) => resolveAlias(String(t), registry))
  const areas = [...new Set(resolved.filter((t) => registry.area.has(t)))].sort()
  return areas.length ? areas : [MISC_AREA]
}

/** Group periphery notes into ordered area buckets (Map area → notes[]). */
function groupByArea(periphery, registry) {
  const byArea = new Map()
  for (const n of periphery) {
    for (const area of noteAreas(n, registry)) {
      if (!byArea.has(area)) byArea.set(area, [])
      byArea.get(area).push(n)
    }
  }
  return byArea
}

/**
 * buildAreaIndexes(opts) — render the per-area on-demand index files
 * (INDEX-<area>.md), each carrying the FULL one-line-per-note entries for its
 * area in the exact grammar of the old flat index (C1/B10). Deterministic like
 * buildIndex: commitHash + dateMap injected, LF endings, area-name-asc order.
 *
 * @param {object} opts  same contract as buildIndex
 * @returns {Array<{file:string, content:string}>}
 */
export function buildAreaIndexes(opts) {
  const {
    corpusDir,
    tagsPath,
    commitHash,
    dateMap = {},
    coreThreshold = CORE_THRESHOLD,
  } = opts

  const registry = loadTagsRegistry(tagsPath)
  const notes = readNotes(corpusDir)
  const cmp = makeComparator(dateMap)
  const periphery = notes.filter((n) => !isCoreNote(n, coreThreshold)).sort(cmp)
  const byArea = groupByArea(periphery, registry)

  const header = GENERATED_MARKER.replace('{commit}', commitHash ?? EPOCH)
  const out = []
  for (const area of [...byArea.keys()].sort()) {
    const lines = []
    lines.push(header)
    lines.push('')
    lines.push(`# INDEX — ${area} (по одной строке на факт)`)
    lines.push('')
    for (const n of byArea.get(area)) lines.push(renderIndexLine(n))
    lines.push('')
    out.push({ file: `INDEX-${area}.md`, content: lines.join('\n') })
  }
  return out
}

// ─────────────────────────── date map (injectable git) ───────────────────────

/**
 * computeDateMap({execGit}) — build a file → last-commit-ISO map from ONE git log
 * pass over the memory dir. The git runner is INJECTED (tests never shell out); in
 * production the CLI passes a runner that invokes:
 *   git log --format=%cI --name-only -- .claude/memory
 * The log is newest-commit-first, so the FIRST time a path is seen is its last
 * commit date. A path missing from the log has no map entry → the comparator's
 * epoch fallback sorts it last (documented; uncommitted files sort to the tail).
 *
 * @param {object} opts
 * @param {(args:string[])=>string} opts.execGit  read-only git runner
 * @param {string} [opts.memoryPathspec]  the pathspec passed to git log
 * @returns {Record<string,string>}  basename → last-commit ISO
 */
export function computeDateMap(opts) {
  const { execGit, memoryPathspec = '.claude/memory' } = opts
  const raw = execGit(['log', '--format=%cI', '--name-only', '--', memoryPathspec])
  const map = {}
  let currentDate = null
  for (const line of String(raw).split('\n')) {
    const trimmed = line.trim()
    if (trimmed === '') continue
    // An ISO-8601 line is a commit-date header; anything else is a file path.
    if (/^\d{4}-\d{2}-\d{2}T/.test(trimmed)) {
      currentDate = trimmed
      continue
    }
    if (currentDate == null) continue
    // Reduce to a basename so the map keys match the corpus file names.
    const base = trimmed.split('/').pop()
    if (!base || !base.endsWith('.md')) continue
    // First seen (newest commit) wins.
    if (!(base in map)) map[base] = currentDate
  }
  return map
}
