/**
 * generator.mjs — the R3 write engine of pillar 1's layered memory.
 *
 * Turns the memory corpus into MEMORY.md = an always-load CORE section (blockers,
 * current-task pointer, top facts) plus a sparse one-line-per-fact index (C1, B9,
 * B10). CORE is generated ONLY from memory notes — the repo instruction file is
 * NEVER an input (D-9-08). Output is byte-deterministic: no clock, no mtime, no HEAD
 * read in the output-producing path — the commit hash and the last-commit date map
 * are INJECTED so lint's MEM-REGEN (49-08) can byte-compare a committed artifact
 * against a fresh regeneration, and so the flip (49-14) can prove determinism.
 *
 * DETERMINISM CONTRACT (T-49-09-01):
 *   - commitHash + dateMap are arguments, never read from the environment here.
 *   - The single ordering comparator (importance desc → dateMap desc → name asc)
 *     is shared with the loader (49-09 loader.mjs imports orderNotes), so both the
 *     written index and the read-time query resolve ties the same way.
 *   - LF line endings, UTF-8 no BOM, sparse by threshold (B9 — no cataloguing).
 *
 * Exports (imported by lint 49-08 MEM-REGEN, flip 49-14):
 *   - GENERATED_MARKER : the single header line carrying 'GENERATED' + the build
 *     command name + a {commit} placeholder + the do-not-hand-edit warning.
 *   - buildIndex({corpusDir, tagsPath, commitHash, dateMap, coreThreshold}) → string
 *   - computeDateMap({execGit}) → {path: last-commit-ISO} from ONE git log pass
 *
 * Corpus access is ONLY through frontmatter.mjs (parseNote + loadTagsRegistry) —
 * the single shared read path (49-04). Node built-ins only; zero npm deps.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'

import { parseNote, loadTagsRegistry, resolveAlias } from './frontmatter.mjs'

/** Importance at/above which a note is CORE (always loaded). Sparse by design (B9). */
export const CORE_THRESHOLD = 9

/**
 * GENERATED_MARKER — the exact header line lint MEM-REGEN greps to know the index
 * is a machine artifact. `{commit}` is substituted with the injected build hash.
 * A single HTML comment so it renders invisibly in the markdown index.
 */
export const GENERATED_MARKER =
  '<!-- GENERATED by scripts/sma memory index at commit {commit} — do not hand-edit; regenerate instead (машинный артефакт, не редактировать вручную) -->'

/** Structural files that are not notes — never fed to the generator. */
const STRUCTURAL_FILES = new Set(['MEMORY.md', 'ARCHIVE.md', 'TAGS.md'])

/** The FI-11 per-area index files are structural artifacts, never notes. */
function isStructuralFile(f) {
  return STRUCTURAL_FILES.has(f) || /^INDEX-[^/\\]+\.md$/.test(f)
}

/** The discovery-block fallback area for a note carrying no registered area tag. */
const MISC_AREA = 'misc'

/** Epoch fallback for a note with no dateMap entry (uncommitted → sorts last). */
const EPOCH = '0000-00-00T00:00:00Z'

/** kind subsection order inside CORE: active state first, then rules, then rest. */
const CORE_KIND_ORDER = ['status', 'procedural-rule', 'decision', 'reference', 'episodic', 'bug-lesson']

// ─────────────────────────── corpus read ─────────────────────────────────────

/** List note files (*.md, non-structural), sorted for a stable base order. */
function listNoteFiles(corpusDir) {
  let entries
  try {
    entries = readdirSync(corpusDir)
  } catch {
    return []
  }
  return entries
    .filter((f) => f.endsWith('.md') && !isStructuralFile(f))
    .filter((f) => {
      try {
        return statSync(join(corpusDir, f)).isFile()
      } catch {
        return false
      }
    })
    .sort()
}

/**
 * Read + parse every corpus note into a uniform record. A note whose frontmatter
 * fails to parse (or is missing) is skipped from the generated index — lint owns
 * schema errors (MEM-SCHEMA); the generator stays fail-soft (never crashes on a
 * bad note, so a regen during a partial migration still produces a stable file).
 *
 * Exported for trim.mjs (9.1-13): the trimmer sizes/demotes CORE through the
 * SAME read + render path the generator writes with — one membership truth.
 */
export function readNotes(corpusDir) {
  const notes = []
  for (const file of listNoteFiles(corpusDir)) {
    let text
    try {
      text = readFileSync(join(corpusDir, file), 'utf8')
    } catch {
      continue
    }
    let fm
    try {
      fm = parseNote(text, { file }).frontmatter
    } catch {
      continue
    }
    if (fm == null) continue
    const importance = Number(fm.importance)
    notes.push({
      file,
      description: typeof fm.description === 'string' ? fm.description.trim() : '',
      kind: String(fm.kind ?? '').trim(),
      tags: Array.isArray(fm.tags) ? fm.tags : [],
      useWhen: String(fm['use-when'] ?? '').trim(),
      importance: Number.isFinite(importance) ? importance : 0,
    })
  }
  return notes
}

// ─────────────────────────── ordering (single truth) ─────────────────────────

/**
 * makeComparator(dateMap) — the ONE ordering key shared by the generator and the
 * loader (49-09): importance desc → injected last-commit date desc → name asc.
 * Recency is NEVER the primary filter (R4). A missing dateMap entry sorts last.
 *
 * Exported so loader.mjs can import a single ordering truth (T-49-09-01).
 *
 * @param {Record<string,string>} dateMap  file → last-commit ISO
 * @returns {(a:{file:string,importance:number}, b:{file:string,importance:number})=>number}
 */
export function makeComparator(dateMap = {}) {
  return (a, b) => {
    if (b.importance !== a.importance) return b.importance - a.importance
    const da = dateMap[a.file] ?? EPOCH
    const db = dateMap[b.file] ?? EPOCH
    if (db !== da) return db < da ? -1 : 1 // date desc
    return a.file < b.file ? -1 : a.file > b.file ? 1 : 0 // name asc
  }
}

// ─────────────────────────── rendering ───────────────────────────────────────

/**
 * Max chars of a description rendered into one line (memory-hygiene C1: one line
 * per fact, under ~200 chars — the detail lives in the note file the line links to).
 * MEMORY.md is always-loaded context; unbounded descriptions ballooned it past the
 * harness partial-load limit (2026-07-03: 64 KB, only partially loaded).
 */
const LINE_DESC_MAX = 200

/** Truncate at the cap on a whole word, marking the cut with an ellipsis. */
function truncateClaim(s) {
  if (s.length <= LINE_DESC_MAX) return s
  const cut = s.slice(0, LINE_DESC_MAX - 1)
  const atWord = cut.replace(/\s+\S*$/, '')
  return `${(atWord.length >= LINE_DESC_MAX / 2 ? atWord : cut).trimEnd()}…`
}

/** Letters/digits only, lowercased — the corpus's echo use-whens drop punctuation. */
function normalizeForEcho(s) {
  return s.toLowerCase().replace(/[^\p{L}\p{N}]/gu, '')
}

/**
 * The bulk-migrated corpus auto-filled use-when as 'при работе с: <first words of
 * the description>' — a pure echo that doubled almost every index line. Render only
 * a use-when that carries its own signal; a genuine trigger ('перед пушем', 'в
 * начале любой сессии') never matches the echo shape and is kept.
 */
function renderableUseWhen(n) {
  if (!n.useWhen) return ''
  const m = n.useWhen.match(/^при работе с:\s*(.*)$/iu)
  if (m == null) return truncateClaim(n.useWhen)
  const probe = normalizeForEcho(m[1])
  if (probe === '' || normalizeForEcho(n.description).startsWith(probe)) return ''
  return truncateClaim(n.useWhen)
}

/**
 * CORE line: a standalone claim + its use-when (agents read this every load).
 * The claim is a markdown link `[desc](file)` so the note path is a real link that
 * the lint MEM-ORPHAN parser (which recognizes `](name.md)`) sees — CORE notes are
 * part of the index, not orphans. Bold-wrapped so CORE still reads as emphasized.
 */
function renderCoreLine(n) {
  const useWhen = renderableUseWhen(n)
  return `- **[${truncateClaim(n.description)}](${n.file})**${useWhen ? ` — ${useWhen}` : ''}`
}
// trim.mjs (9.1-13) sizes CORE demotions with the exact render the generator
// writes — exported so the byte math cannot drift from the artifact.
export { renderCoreLine }

/**
 * Index line (B10): a standalone claim + kind + tags + use-when + path, so an agent
 * judges relevance WITHOUT opening the file. One line per fact (C1).
 */
function renderIndexLine(n) {
  const tags = n.tags.join(', ')
  const useWhen = renderableUseWhen(n)
  return `- [${truncateClaim(n.description)}](${n.file}) · ${n.kind} · ${tags}${useWhen ? ` · ${useWhen}` : ''}`
}

/** Order the CORE notes: kind subsection order, then the shared comparator within. */
function orderCore(coreNotes, cmp) {
  const rank = (k) => {
    const i = CORE_KIND_ORDER.indexOf(k)
    return i === -1 ? CORE_KIND_ORDER.length : i
  }
  return coreNotes.slice().sort((a, b) => {
    const ra = rank(a.kind)
    const rb = rank(b.kind)
    if (ra !== rb) return ra - rb
    return cmp(a, b)
  })
}

/**
 * buildIndex(opts) — render the whole MEMORY.md artifact deterministically.
 *
 * @param {object} opts
 * @param {string} opts.corpusDir      directory of the memory notes
 * @param {string} opts.tagsPath       path to TAGS.md (facet registry; parsed for stats)
 * @param {string} opts.commitHash     the build-anchor commit (INJECTED — never read here)
 * @param {Record<string,string>} [opts.dateMap]  file → last-commit ISO (INJECTED)
 * @param {number} [opts.coreThreshold]  importance at/above which a note is CORE
 * @returns {string}  the full generated MEMORY.md text (LF, no BOM)
 */
export function buildIndex(opts) {
  const {
    corpusDir,
    tagsPath,
    commitHash,
    dateMap = {},
    coreThreshold = CORE_THRESHOLD,
  } = opts

  const registry = loadTagsRegistry(tagsPath)

  const notes = readNotes(corpusDir)
  const cmp = makeComparator(dateMap)

  const core = orderCore(
    notes.filter((n) => n.importance >= coreThreshold),
    cmp,
  )
  const periphery = notes.filter((n) => n.importance < coreThreshold).sort(cmp)
  const byArea = groupByArea(periphery, registry)

  const header = GENERATED_MARKER.replace('{commit}', commitHash ?? EPOCH)

  const out = []
  out.push(header)
  out.push('')
  out.push('# MEMORY — сгенерированный индекс памяти (R3)')
  out.push('')
  out.push(`> Построено из коммита \`${commitHash ?? EPOCH}\` · заметок: ${notes.length} · ядро: ${core.length} · индекс: ${periphery.length}.`)
  out.push('')

  // ── CORE (always loaded) ────────────────────────────────────────────────
  out.push('## Ядро (всегда загружается)')
  out.push('')
  if (core.length === 0) {
    out.push('_(пусто)_')
    out.push('')
  } else {
    for (const n of core) out.push(renderCoreLine(n))
    out.push('')
  }

  // ── Thin discovery layer (FI-11, 9.1-13) ───────────────────────────────
  // One line per AREA with a count; the full one-line-per-note catalog lives
  // in the per-area INDEX-<area>.md files, pulled by tag on demand via
  // `pnpm sma load` — always-load stays within its byte budget with zero loss
  // of discoverability.
  out.push('## Обзор областей (полные индексы по требованию — `pnpm sma load --tags <area>`)')
  out.push('')
  if (byArea.size === 0) {
    out.push('_(пусто)_')
    out.push('')
  } else {
    for (const area of [...byArea.keys()].sort()) {
      const count = byArea.get(area).length
      out.push(`- ${area} — заметок: ${count} → [INDEX-${area}.md](INDEX-${area}.md)`)
    }
    out.push('')
  }

  // LF endings, trailing newline, no BOM.
  return out.join('\n')
}

// ─────────────────────────── per-area index files (FI-11) ────────────────────

/**
 * A note's discovery areas: its alias-resolved tags that are registered area
 * facets. A note with several area tags is catalogued in EVERY matching area
 * index (discoverability beats deduplication for a catalog); a note with no
 * registered area tag lands in the `misc` bucket so nothing is uncatalogued.
 */
function noteAreas(n, registry) {
  const resolved = (n.tags ?? []).map((t) => resolveAlias(String(t), registry))
  const areas = [...new Set(resolved.filter((t) => registry.area.has(t)))].sort()
  return areas.length ? areas : [MISC_AREA]
}

/** Group periphery notes into ordered area buckets (Map area → notes[]). */
function groupByArea(periphery, registry) {
  const byArea = new Map()
  for (const n of periphery) {
    for (const area of noteAreas(n, registry)) {
      if (!byArea.has(area)) byArea.set(area, [])
      byArea.get(area).push(n)
    }
  }
  return byArea
}

/**
 * buildAreaIndexes(opts) — render the per-area on-demand index files
 * (INDEX-<area>.md), each carrying the FULL one-line-per-note entries for its
 * area in the exact grammar of the old flat index (C1/B10). Deterministic like
 * buildIndex: commitHash + dateMap injected, LF endings, area-name-asc order.
 *
 * @param {object} opts  same contract as buildIndex
 * @returns {Array<{file:string, content:string}>}
 */
export function buildAreaIndexes(opts) {
  const {
    corpusDir,
    tagsPath,
    commitHash,
    dateMap = {},
    coreThreshold = CORE_THRESHOLD,
  } = opts

  const registry = loadTagsRegistry(tagsPath)
  const notes = readNotes(corpusDir)
  const cmp = makeComparator(dateMap)
  const periphery = notes.filter((n) => n.importance < coreThreshold).sort(cmp)
  const byArea = groupByArea(periphery, registry)

  const header = GENERATED_MARKER.replace('{commit}', commitHash ?? EPOCH)
  const out = []
  for (const area of [...byArea.keys()].sort()) {
    const lines = []
    lines.push(header)
    lines.push('')
    lines.push(`# INDEX — ${area} (по одной строке на факт)`)
    lines.push('')
    for (const n of byArea.get(area)) lines.push(renderIndexLine(n))
    lines.push('')
    out.push({ file: `INDEX-${area}.md`, content: lines.join('\n') })
  }
  return out
}

// ─────────────────────────── date map (injectable git) ───────────────────────

/**
 * computeDateMap({execGit}) — build a file → last-commit-ISO map from ONE git log
 * pass over the memory dir. The git runner is INJECTED (tests never shell out); in
 * production the CLI passes a runner that invokes:
 *   git log --format=%cI --name-only -- .claude/memory
 * The log is newest-commit-first, so the FIRST time a path is seen is its last
 * commit date. A path missing from the log has no map entry → the comparator's
 * epoch fallback sorts it last (documented; uncommitted files sort to the tail).
 *
 * @param {object} opts
 * @param {(args:string[])=>string} opts.execGit  read-only git runner
 * @param {string} [opts.memoryPathspec]  the pathspec passed to git log
 * @returns {Record<string,string>}  basename → last-commit ISO
 */
export function computeDateMap(opts) {
  const { execGit, memoryPathspec = '.claude/memory' } = opts
  const raw = execGit(['log', '--format=%cI', '--name-only', '--', memoryPathspec])
  const map = {}
  let currentDate = null
  for (const line of String(raw).split('\n')) {
    const trimmed = line.trim()
    if (trimmed === '') continue
    // An ISO-8601 line is a commit-date header; anything else is a file path.
    if (/^\d{4}-\d{2}-\d{2}T/.test(trimmed)) {
      currentDate = trimmed
      continue
    }
    if (currentDate == null) continue
    // Reduce to a basename so the map keys match the corpus file names.
    const base = trimmed.split('/').pop()
    if (!base || !base.endsWith('.md')) continue
    // First seen (newest commit) wins.
    if (!(base in map)) map[base] = currentDate
  }
  return map
}
