/**
 * generator.mjs — the R3 write engine of pillar 1's layered memory.
 *
 * Turns the memory corpus into MEMORY.md = an always-load CORE section (blockers,
 * current-task pointer, top facts) plus a sparse one-line-per-fact index (C1, B9,
 * B10). CORE is generated ONLY from memory notes — the repo instruction file is
 * NEVER an input. Output is byte-deterministic: no clock, no mtime, no HEAD
 * read in the output-producing path — the commit hash and the last-commit date map
 * are INJECTED so lint's MEM-REGEN (9-08) can byte-compare a committed artifact
 * against a fresh regeneration, and so the flip (9-14) can prove determinism.
 *
 * DETERMINISM CONTRACT:
 *   - commitHash + dateMap are arguments, never read from the environment here.
 *   - The single ordering comparator (importance desc → dateMap desc → name asc)
 *     is shared with the loader (9-09 loader.mjs imports orderNotes), so both the
 *     written index and the read-time query resolve ties the same way.
 *   - LF line endings, UTF-8 no BOM, sparse by threshold (B9 — no cataloguing).
 *
 * Exports (imported by lint 9-08 MEM-REGEN, flip 9-14):
 *   - GENERATED_MARKER : the single header line carrying 'GENERATED' + the build
 *     command name + a {commit} placeholder + the do-not-hand-edit warning.
 *   - buildIndex({corpusDir, tagsPath, commitHash, dateMap, coreThreshold}) → string
 *   - computeDateMap({execGit}) → {path: last-commit-ISO} from ONE git log pass
 *
 * TWO SCHEMA VERSIONS, ONE INDEX: the corpus may hold v1 notes and schema-v2
 * records side by side, and both are read through the same parser. Where the two
 * grammars name the same thing differently, this module maps them onto one axis
 * rather than growing a second rendering path:
 *   description ~ claim · kind ~ (memory_type, truth_mode) · tags ~ retrieval.areas ·
 *   importance≥threshold ~ context_priority: always.
 * On top of that sits ONE filter that outranks all of it: a record whose status
 * names any of the four retirements (superseded · revoked · expired · archived)
 * never reaches CORE (see CORE_EXCLUDED_STATUSES).
 *
 * EPISODES ARE INVISIBLE HERE BY CONSTRUCTION. `.claude/memory/episodes/` is a
 * subdirectory, and the corpus listing below is FLAT (readdirSync + isFile), so
 * no episode can reach the always-load payload even if someone forgets it
 * exists. That is asserted positively in the suite: adding an episode leaves the
 * generated bytes identical. Do not "fix" the listing into a recursive walk.
 *
 * Corpus access is ONLY through frontmatter.mjs (parseNote + loadTagsRegistry) —
 * the single shared read path (9-04). Node built-ins only; zero npm deps.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'

import { parseNote, loadTagsRegistry, resolveAlias } from './frontmatter.mjs'
import { SENSITIVITY_CLASSES } from './schema-v2.mjs'

/** Importance at/above which a note is CORE (always loaded). Sparse by design (B9). */
export const CORE_THRESHOLD = 9

/**
 * Lifecycle states that can NEVER reach always-load context, whatever else the
 * record says about itself. A superseded rule and a revoked one are not merely
 * less important — they are known to be wrong, and an index that keeps quoting
 * them into every session is worse than one that never learned them. They stay
 * catalogued in their area index (findable, with the state named) and out of CORE.
 *
 * ALL FOUR RETIREMENTS, NOT TWO. This set held `{superseded, revoked}` until
 * 2026-08-04 while the WRITE path retired four states — `write-pipeline.mjs`
 * `LIFECYCLE_ACTIONS` and `migrate-v1-v2.mjs` `RETIRED_STATUSES` both name
 * `expired` and `archived` too — so a record the pipeline had archived was still
 * delivered, and `MEMORY-LIFECYCLE.md` §5.4's promise («removed from active
 * retrieval, kept for history») was not kept by any code. The gap was recorded
 * as D-11-DEFER-01 and closed by plan 11-14, which put the retirement states
 * behind a user-facing verb: `memory forget --archive` that leaves the record
 * quotable is a verb that lies about what it did.
 *
 * The word means «this record has been retired by a decision», so `expired`
 * belongs here on the record's own say-so, independently of the `valid_until`
 * window that `visibilityVerdict` checks separately — a record can be stamped
 * expired before its date, and the stamp is the newer statement.
 */
export const CORE_EXCLUDED_STATUSES = new Set(['superseded', 'revoked', 'expired', 'archived'])

/**
 * What a schema-v2 grade is worth on the shared weight axis.
 *
 * v2 has no `importance` number: the migration split it into `criticality` (what
 * does MISSING this memory cost) and `context_priority` (must it always load).
 * `context_priority` was already read back onto the axis; `criticality` was not,
 * so every on-demand v2 record weighed 0 — and a consumer that tiers by weight
 * (the reflex fatigue battery silences ≤ 3) heard nothing from migrated knowledge
 * at all. The grades are the missing half of that inverse, in ONE place: no
 * consumer gets its own table (the one-axis law of this module's header).
 *
 * The numbers are the owner's semantics, not a derivation, and they were approved
 * as such: high 8 — loud enough for the verbose tier; medium 5 — a one-liner;
 * low 2 — deliberately BELOW the silence threshold, because a record that says
 * missing it costs little has not earned an interruption. `critical` is the
 * fourth grade of the documented ladder (docs/MEMORY-MODEL.md §8) and is held at
 * the `high` value: the severest grade must never be quieter than `high`, and no
 * tier louder than the approved one is invented here.
 *
 * A grade outside the ladder contributes nothing — an unknown word must not
 * silently mint a weight.
 */
export const CRITICALITY_WEIGHTS = Object.freeze({ low: 2, medium: 5, high: 8, critical: 8 })

/**
 * The CORE membership question, asked ONCE for both schema versions:
 *   - a retired record is never CORE (the hard filter above);
 *   - a schema-v2 record states its own answer in `context_priority` — v2 has no
 *     `importance` field at all, so the threshold cannot speak for it;
 *   - everything else is the v1 law, unchanged: importance at/above threshold.
 *
 * Exported so a consumer sizing or trimming CORE asks the same question the
 * writer answered, instead of re-deriving membership from a field list.
 */
export function isCoreNote(n, coreThreshold = CORE_THRESHOLD) {
  if (CORE_EXCLUDED_STATUSES.has(n.status)) return false
  // A caller may raise the bar out of reach on purpose (`coreThreshold:
  // Infinity` — the reflex matcher's way of saying «there is no CORE here, route
  // every record through facet matching»). An unreachable bar means an EMPTY
  // core, so the v2 shortcut below must not smuggle records past it.
  if (!Number.isFinite(coreThreshold)) return n.importance >= coreThreshold
  if (n.contextPriority === 'always') return true
  if (n.contextPriority === 'on-demand') return false
  return n.importance >= coreThreshold
}

// ───────────────── read-time visibility (hard filters, docs §9.1) ────────────

/**
 * The sensitivity ceiling each named audience may be shown, as a class from the
 * schema's own closed vocabulary (no second dictionary is minted here).
 *
 *   owner    — the local human reading their own corpus: nothing is withheld.
 *              Filtering here would cost recall on one's own material while
 *              protecting nobody, so it is the default.
 *   subagent — a delegated agent: public + internal.
 *   export   — anything leaving the machine (a shared pack, a report): public only.
 *
 * An audience named directly as a sensitivity class reads as that ceiling. An
 * audience nobody registered is fail-CLOSED to the narrowest ceiling: an unknown
 * consumer is not a trusted one.
 */
export const AUDIENCE_SENSITIVITY_CEILING = Object.freeze({
  owner: null, // null = no ceiling
  subagent: 'internal',
  export: 'public',
})

/** The class an undeclared record is treated as: absence is never `public`. */
const UNDECLARED_SENSITIVITY = 'internal'

/** A date-only stamp (`YYYY-MM-DD`) — the corpus writes both this and full ISO. */
const DATE_ONLY = /^\d{4}-\d{2}-\d{2}$/

/**
 * A frontmatter time stamp as epoch ms, or null when absent/unparseable.
 * A date-only stamp is read as the WHOLE day: `valid_from` starts at its first
 * instant, `valid_until` runs through its last. That is the conservative reading —
 * a record stamped «valid until the 18th» is still valid ON the 18th, and hiding
 * knowledge is the expensive mistake here. An unparseable stamp yields null (a
 * schema finding the lint owns), never a silent removal from delivery.
 */
function instantOf(value, { endOfDay = false } = {}) {
  const raw = value instanceof Date ? value.toISOString() : String(value ?? '').trim()
  if (raw === '') return null
  const iso = DATE_ONLY.test(raw) ? `${raw}T${endOfDay ? '23:59:59.999' : '00:00:00.000'}Z` : raw
  const ms = Date.parse(iso)
  return Number.isFinite(ms) ? ms : null
}

/** Position of a sensitivity class in the schema's ordered vocabulary, or -1. */
function sensitivityRank(value) {
  return SENSITIVITY_CLASSES.indexOf(String(value ?? '').trim())
}

/** The ceiling for an audience, or null when the audience may see every class. */
function ceilingFor(audience) {
  const named = String(audience ?? '').trim()
  if (named === '' || named === 'owner') return null
  if (Object.hasOwn(AUDIENCE_SENSITIVITY_CEILING, named)) return AUDIENCE_SENSITIVITY_CEILING[named]
  if (SENSITIVITY_CLASSES.includes(named)) return named
  return SENSITIVITY_CLASSES[0] // fail-closed: an unregistered audience sees public only
}

/**
 * One dimension of `scope` (repos / environments): a record that names a world
 * it holds in is out of delivery in every OTHER world. A record that names none
 * constrains nothing, and a caller that states no world asks no question — the
 * filter only narrows when BOTH sides have something to say.
 *
 * Returns null when the dimension allows the record through, and the two sides of
 * the disagreement when it does not — because «withheld» without «by what, against
 * what» is the kind of answer that makes a retrieval layer unfalsifiable.
 */
function scopeDenial(scope, key, asked) {
  const value = String(asked ?? '').trim()
  if (value === '') return null
  const raw = scope?.[key]
  const declared = (Array.isArray(raw) ? raw : raw == null ? [] : [raw])
    .map((s) => String(s).trim())
    .filter((s) => s !== '')
  if (declared.length === 0 || declared.includes(value)) return null
  return { declared, asked: value }
}

/**
 * The reason names of the read-time filters, frozen and owned HERE — by the module
 * that runs them. Every consumer that reports why a record was withheld imports
 * these; a second copy of the vocabulary would be a second answer waiting to drift
 * from the code that actually decides.
 */
export const VISIBILITY_REASONS = Object.freeze({
  STATUS_RETIRED: 'status-retired',
  NOT_YET_VALID: 'not-yet-valid',
  EXPIRED: 'expired',
  SENSITIVITY_CEILING: 'sensitivity-ceiling',
  SCOPE_REPO: 'scope-repo',
  SCOPE_ENVIRONMENT: 'scope-environment',
})

/**
 * visibilityVerdict(note, opts) — the SAME four hard filters as isVisibleNow, with
 * their verdict spelled out: `null` when the record may be shown, otherwise the
 * reason code plus the field and value that decided it.
 *
 * This is the single implementation of read-time visibility; `isVisibleNow` is the
 * boolean question asked of it. Splitting them the other way round — a boolean
 * filter here and a «why» reconstructed elsewhere — is exactly how an explanation
 * starts describing a retrieval nobody runs.
 *
 * @param {object} note  a projected record (projectNoteAxis — the shared axis)
 * @param {{now?:string|Date, audience?:string, scope?:{repo?:string, environment?:string}}} [opts]
 * @returns {null|{reason:string, field:string, value:*}}
 */
export function visibilityVerdict(note, opts = {}) {
  const n = note ?? {}

  // 1. status — the filter that already ran at CORE membership, now on every path.
  if (CORE_EXCLUDED_STATUSES.has(n.status)) {
    return { reason: VISIBILITY_REASONS.STATUS_RETIRED, field: 'status', value: n.status }
  }

  // 2. valid time — the window the record itself declares (bi-temporal, B5).
  const now = instantOf(opts.now) ?? Date.now()
  const from = instantOf(n.validFrom)
  if (from != null && now < from) {
    return { reason: VISIBILITY_REASONS.NOT_YET_VALID, field: 'valid_from', value: n.validFrom }
  }
  const until = instantOf(n.validUntil, { endOfDay: true })
  if (until != null && now > until) {
    return { reason: VISIBILITY_REASONS.EXPIRED, field: 'valid_until', value: n.validUntil }
  }

  // 3. sensitivity — by AUDIENCE only. The local owner (default) is withheld nothing.
  const ceiling = ceilingFor(opts.audience)
  if (ceiling != null) {
    const declared = String(n.sensitivity ?? '').trim()
    const effective = declared === '' ? UNDECLARED_SENSITIVITY : declared
    const rank = sensitivityRank(effective)
    const base = { field: 'sensitivity', value: declared, effective, audience: String(opts.audience ?? ''), ceiling }
    // a class outside the vocabulary is fail-closed — an unreadable label is not a permit
    if (rank < 0) return { reason: VISIBILITY_REASONS.SENSITIVITY_CEILING, ...base, unknown_class: true }
    if (rank > sensitivityRank(ceiling)) return { reason: VISIBILITY_REASONS.SENSITIVITY_CEILING, ...base }
  }

  // 4. scope — the repo/environment world the claim is meant to hold in (§9.2).
  const scope = n.scope ?? {}
  const repoDenial = scopeDenial(scope, 'repos', opts.scope?.repo)
  if (repoDenial) return { reason: VISIBILITY_REASONS.SCOPE_REPO, field: 'scope.repos', value: repoDenial.declared, asked: repoDenial.asked }
  const envDenial = scopeDenial(scope, 'environments', opts.scope?.environment)
  if (envDenial) {
    return { reason: VISIBILITY_REASONS.SCOPE_ENVIRONMENT, field: 'scope.environments', value: envDenial.declared, asked: envDenial.asked }
  }

  return null
}

/**
 * isVisibleNow(note, opts) — MAY this record be shown right now, to this consumer.
 *
 * The read-time half of `docs/MEMORY-MODEL.md` §9.1: hard filters run BEFORE any
 * ranking — status, valid time, sensitivity by audience, repo/environment scope.
 * Structural only: it reads typed fields and never the note's body, so nothing a
 * record says in prose can argue its way into a payload.
 *
 * This is deliberately NOT the write-time approval ladder (`resolveApprovalPath`,
 * schema-v2): that answers «may this record EXIST», this answers «may it be SHOWN».
 * The two read some of the same fields and must not be collapsed into one function —
 * merging them would make a read path enforce write policy and vice versa.
 *
 * Nothing here mutates: an expired record keeps its `status`, and the lint's
 * advisory MEM-EXPIRE finding stays the human-facing consumer of the same field.
 *
 * @param {object} note  a projected record (projectNoteAxis — the shared axis)
 * @param {{now?:string|Date, audience?:string, scope?:{repo?:string, environment?:string}}} [opts]
 *        now      — injected for determinism; defaults to the current instant
 *        audience — the consumer class (default: the local owner, unfiltered)
 *        scope    — the world the caller is asking from (repo / environment)
 * @returns {boolean}
 */
export function isVisibleNow(note, opts = {}) {
  return visibilityVerdict(note, opts) === null
}

// ──────────── read-time trust (the sibling filter, docs §9 · D-11-07) ─────────

/**
 * INJECTION_MARKERS — the shapes of text that count as AN INSTRUCTION AIMED AT THE
 * READER rather than a claim about the world.
 *
 * The list is deliberately SHORT, NAMED and each entry states why it is a marker. A
 * long unexplained regex list is the artifact that quietly gets tuned until a benchmark
 * goes green, and at that point the filter measures the benchmark instead of the
 * threat. Three shapes are the whole standard indirect-prompt-injection grammar, and
 * anything a fourth would catch belongs in a review, not in a silent regex.
 *
 * Both languages the corpus is written in are covered in each marker, because a
 * detector that only reads English would make «write the attack in Russian» the
 * bypass.
 *
 * The patterns are applied to a NORMALIZED body (blockquote markers stripped, all
 * whitespace collapsed to single spaces) so an attack does not become invisible by
 * being line-wrapped or quoted — which is exactly how the benchmark's own carrier is
 * written. `[^.]{0,N}` keeps every match inside one sentence: a verb in one sentence
 * and a noun three sentences later is not an imperative, it is prose.
 *
 * WHY THE RUSSIAN HALVES DO NOT USE `\b` OR `\w`. JavaScript's `\w` is
 * `[A-Za-z0-9_]` and its `\b` is defined in terms of it, so BOTH ARE BLIND TO
 * CYRILLIC: a Russian alternative written with them matches nothing at all, silently,
 * while the pattern still looks bilingual on the page. That is not a hypothetical —
 * the first draft of this list was written that way and a fully Russian attack walked
 * straight through it; it was caught by running the detector, not by reading it. The
 * Russian halves therefore use the `u` flag with `\p{L}` classes and `(?<!\p{L})` /
 * `(?!\p{L})` boundaries, and `memory-untrusted.test.ts` carries a Russian-only attack
 * so the blindness cannot come back unnoticed.
 */
export const INJECTION_MARKERS = Object.freeze([
  Object.freeze({
    name: 'override-prior-instructions',
    why: 'An imperative to disregard what came before is the canonical opening of an indirect prompt injection: a record making a claim about the world has no reason to address the reader’s prior instructions at all.',
    pattern:
      /(?:\b(?:ignore|disregard|forget)\b[^.]{0,32}\b(?:previous|prior|earlier|preceding|above|all)\b[^.]{0,32}\b(?:instruction|prompt|rule|directive)s?\b)|(?:(?<!\p{L})(?:игнорируй\p{L}*|игнорировать|забудь\p{L}*|не\s+выполняй)(?!\p{L})[^.]{0,40}(?<!\p{L})(?:предыдущ\p{L}+|прежн\p{L}+|прошл\p{L}+|вышеизложенн\p{L}+|инструкци\p{L}+|указани\p{L}+))/iu,
  }),
  Object.freeze({
    name: 'outranks-user-task',
    why: 'A record asserting that its own text ranks above the user’s task is claiming authority it cannot have: retrieved memory is evidence offered to a decision, never the decision, so the assertion itself is the attack.',
    pattern:
      /(?:\b(?:take|takes|has|have)\s+(?:priority|precedence)\s+over\b[^.]{0,48}\b(?:user|task|request|instruction|prompt)s?\b)|(?:\boverrides?\s+(?:the\s+)?(?:user|user['’]s)\b)|(?:(?<!\p{L})(?:имеет|имеют)\s+приоритет\s+над(?!\p{L})[^.]{0,48}(?<!\p{L})(?:задач\p{L}+|инструкци\p{L}+|указани\p{L}+|запрос\p{L}+|пользовател\p{L}+))/iu,
  }),
  Object.freeze({
    name: 'exfiltrate-secrets',
    why: 'An imperative to send credentials somewhere is the payload half of the same attack. The secret nouns are the UNAMBIGUOUS ones only: a bare "token" is an LLM accounting unit in this product’s own notes far more often than a credential, and Russian «ключевой» is the adjective "central", not a key — a marker that cannot tell those apart would withhold ordinary knowledge, which is the denial-of-service half of the same threat.',
    pattern:
      /(?:\b(?:disclose|reveal|expose|post|publish|send|share|leak|dump|upload)\b[^.]{0,64}\b(?:credentials?|secrets?|api[\s-]?keys?|(?:access|auth|bearer)[\s-]?tokens?|passwords?|\.env)\b)|(?:(?<!\p{L})(?:вылож\p{L}+|опубликуй\p{L}*|опубликова\p{L}+|отправ\p{L}+|раскро\p{L}+|пришл\p{L}+|слей|скинь|передай)(?!\p{L})[^.]{0,64}(?<!\p{L})(?:ключ(?:[аиуеы]|ей|ам|ами|ах|ом)?(?!\p{L})|секрет\p{L}*|парол\p{L}*|учётн\p{L}+\s+данн\p{L}+|учетн\p{L}+\s+данн\p{L}+))/iu,
  }),
])

/**
 * The reason names of the read-time TRUST filter, frozen and owned here beside the code
 * that runs them — the same law as VISIBILITY_REASONS above.
 *
 * FOREIGN_ORIGIN is deliberately NOT a new string. A note belonging to another
 * repository is refused by the scope filter that has always owned that question, and
 * minting a second name for the same verdict would give one decision two vocabularies
 * and let them drift. It is aliased here so a consumer reading only this map still
 * finds the foreign-origin answer under a name it recognises.
 */
export const UNTRUSTED_REASONS = Object.freeze({
  SUSPICIOUS_INSTRUCTION: 'suspicious-instruction',
  UNREADABLE_BODY: 'unreadable-body',
  FOREIGN_ORIGIN: VISIBILITY_REASONS.SCOPE_REPO,
})

/**
 * scanBodyForInjection(body) → {unreadable, markers[]}.
 *
 * Called ONCE per record, in `readNotes`, where the file text is already in memory —
 * so the corpus is still read in a single pass and no second read path is introduced.
 * What travels onward is the VERDICT MATERIAL (a boolean and the matched marker names),
 * never the body: a trace that quoted the attack back would carry the payload into the
 * very place the filter exists to keep it out of.
 */
function scanBodyForInjection(body) {
  if (typeof body !== 'string') return { unreadable: true, markers: [] }
  const normalized = body
    .replace(/^[ \t]*>+[ \t]?/gm, ' ') // a quoted attack is still an attack
    .replace(/\s+/g, ' ')
  const markers = []
  for (const m of INJECTION_MARKERS) if (m.pattern.test(normalized)) markers.push(m.name)
  return { unreadable: false, markers }
}

/**
 * untrustedVerdict(note, opts) — MAY this record be BELIEVED, as opposed to shown.
 *
 * The sibling of `visibilityVerdict`, not a fifth check inside it. That separation is
 * the whole point: `visibilityVerdict`'s docstring states that it reads typed fields and
 * never a body, and that law is what makes the structural filter auditable. Folding a
 * body scan into it would quietly retire the law while leaving the sentence in place.
 *
 * This function ALSO reads typed fields only — `injectionMarkers` and `bodyUnreadable`
 * are computed at parse time (scanBodyForInjection) and carried on the projected axis
 * like any other field. The body itself never reaches here.
 *
 * FAIL-CLOSED, per the threat model's own rule (docs/MEMORY-THREAT-MODEL.md §3): «a
 * subsystem that only improves an answer may degrade; a subsystem that decides what may
 * be believed... must refuse.» A body that could not be read is therefore a refusal, not
 * a pass — an unreadable record is precisely the one whose contents nobody checked.
 *
 * @param {object} note  a projected record (projectNoteAxis — the shared axis)
 * @param {object} [opts] reserved for symmetry with visibilityVerdict; unread today
 * @returns {null|{reason:string, field:string, value:*, markers?:string[]}}
 */
export function untrustedVerdict(note, opts = {}) {
  const n = note ?? {}
  void opts
  if (n.bodyUnreadable === true) {
    return { reason: UNTRUSTED_REASONS.UNREADABLE_BODY, field: 'body', value: null }
  }
  const markers = Array.isArray(n.injectionMarkers) ? n.injectionMarkers : []
  if (markers.length > 0) {
    return { reason: UNTRUSTED_REASONS.SUSPICIOUS_INSTRUCTION, field: 'body', value: markers[0], markers: [...markers] }
  }
  return null
}

/**
 * GENERATED_MARKER — the exact header line lint MEM-REGEN greps to know the index
 * is a machine artifact. `{commit}` is substituted with the injected build hash.
 * A single HTML comment so it renders invisibly in the markdown index.
 */
export const GENERATED_MARKER =
  '<!-- GENERATED by scripts/sma memory index at commit {commit} — do not hand-edit; regenerate instead (машинный артефакт, не редактировать вручную) -->'

/**
 * Structural files that are not notes — never fed to the generator.
 * `listNoteFiles` below is exported for the same one-implementation reason: a
 * consumer that has to account for EVERY note in the corpus (the retrieval
 * explainer) must ask this module what counts as a note, not re-derive the answer
 * from a directory listing and a second idea of what is structural.
 */
const STRUCTURAL_FILES = new Set(['MEMORY.md', 'ARCHIVE.md', 'TAGS.md'])

/** The FI-11 per-area index files are structural artifacts, never notes. */
function isStructuralFile(f) {
  return STRUCTURAL_FILES.has(f) || /^INDEX-[^/\\]+\.md$/.test(f)
}

/** The discovery-block fallback area for a note carrying no registered area tag. */
const MISC_AREA = 'misc'

/** Epoch fallback for a note with no dateMap entry (uncommitted → sorts last). */
const EPOCH = '0000-00-00T00:00:00Z'

/** kind subsection order inside CORE: active state first, then rules, then rest. */
const CORE_KIND_ORDER = ['status', 'procedural-rule', 'decision', 'reference', 'episodic', 'bug-lesson']

// ─────────────────────────── corpus read ─────────────────────────────────────

/** List note files (*.md, non-structural), sorted for a stable base order. */
export function listNoteFiles(corpusDir) {
  let entries
  try {
    entries = readdirSync(corpusDir)
  } catch {
    return []
  }
  return entries
    .filter((f) => f.endsWith('.md') && !isStructuralFile(f))
    .filter((f) => {
      try {
        return statSync(join(corpusDir, f)).isFile()
      } catch {
        return false
      }
    })
    .sort()
}

/**
 * Read + parse every corpus note into a uniform record. A note whose frontmatter
 * fails to parse (or is missing) is skipped from the generated index — lint owns
 * schema errors (MEM-SCHEMA); the generator stays fail-soft (never crashes on a
 * bad note, so a regen during a partial migration still produces a stable file).
 *
 * Exported for trim.mjs: the trimmer sizes/demotes CORE through the
 * SAME read + render path the generator writes with — one membership truth.
 */
export function readNotes(corpusDir) {
  const notes = []
  for (const file of listNoteFiles(corpusDir)) {
    let text
    try {
      text = readFileSync(join(corpusDir, file), 'utf8')
    } catch {
      continue
    }
    let parsed
    try {
      parsed = parseNote(text, { file })
    } catch {
      continue
    }
    const fm = parsed.frontmatter
    if (fm == null) continue
    // The body-derived trust signal is computed HERE — the one place the file text is
    // already in memory — and only its VERDICT MATERIAL is carried onward. One corpus
    // read, and `untrustedVerdict` still reads typed fields like its sibling.
    notes.push(
      projectNoteAxis(fm, {
        file,
        schemaVersion: parsed.schemaVersion,
        bodyScan: scanBodyForInjection(parsed.body),
      }),
    )
  }
  return notes
}

/**
 * projectNoteAxis(frontmatter, {file, schemaVersion}) — THE one-axis projection,
 * in ONE place.
 *
 * Every consumer that asks a corpus record "what is your claim / your kind / your
 * areas / are you always-load" goes through this function, so the two grammars
 * can never grow two answers. The mapping (also stated in the module header):
 *   description ~ claim · kind ~ (memory_type, truth_mode) · tags ~ retrieval.areas ·
 *   importance≥CORE_THRESHOLD ~ context_priority: always · importance ~ criticality ·
 *   use-when ~ retrieval.hint · use-when-pattern ~ retrieval.paths[0] ·
 *   reflex ~ retrieval.reflex.
 *
 * The importance pairs are the migration's own inverse, not a new invention:
 * migrate-v1-v2.mjs writes `context_priority: importance >= 9 ? always : on-demand`
 * AND `criticality: importance >= 8 ? high : medium`, so reading both back —
 * `always` as the CORE_THRESHOLD floor, the grade as the number under it
 * (CRITICALITY_WEIGHTS) — round-trips a migrated note to where it started. A v2
 * record still states no importance of its own: `importance` on the axis stays 0
 * for it, and only `weight` (the ordering and tiering key) carries the grade.
 *
 * Exported for loader.mjs (retrieval) and context-pack.mjs (pointer lines): the
 * read engine and the compiler read the SAME axis the index is written with.
 *
 * @param {object} fm  parsed frontmatter (v1 or v2)
 * @param {{file?:string, schemaVersion?:1|2, bodyScan?:{unreadable:boolean, markers:string[]}}} [meta]
 *        bodyScan — the ONE body-derived signal, computed by readNotes at parse time.
 *        Absent for a caller that only wants the axis; see the trust fields below.
 * @returns {{file:string, description:string, kind:string, tags:string[], useWhen:string,
 *            importance:number, status:string, contextPriority:string, schemaVersion:1|2,
 *            weight:number, hint:string, pathPattern:string, reflexOptOut:boolean}}
 */
export function projectNoteAxis(fm, meta = {}) {
  const source = fm ?? {}
  const importance = Number(source.importance)
  const stated = Number.isFinite(importance)
  const imp = stated ? importance : 0
  const contextPriority = String(source.context_priority ?? '').trim()
  const retrieval = retrievalBlock(source)
  // The base of the weight axis. A record that STATES a number is that number —
  // a stated 0 is a statement, not a gap to be filled in — and only a record with
  // no number at all (every schema-v2 record) falls through to its grade.
  const graded = CRITICALITY_WEIGHTS[String(source.criticality ?? '').trim().toLowerCase()] ?? 0
  const base = stated ? imp : graded
  return {
    file: meta.file ?? '',
    // v1 says `description`, v2 says `claim` — one line about one fact, under
    // two names. Same slot in the rendered index either way.
    description: renderableText(source.description ?? source.claim),
    // v1 `kind` and v2 (memory_type, truth_mode) both answer "what sort of
    // knowledge is this" — see projectKind for the one collapsed pair.
    kind: projectKind(source),
    // v1 `tags` and v2 `retrieval.areas` are the SAME membership axis (1:1),
    // so the area grouping (and the loader's facet matching) needs no second path.
    tags: mergeAreas(source),
    useWhen: renderableText(source['use-when']),
    importance: imp,
    status: renderableText(source.status),
    contextPriority,
    schemaVersion: meta.schemaVersion ?? 1,
    // The ordering key. v2 carries no importance, so BOTH halves of what the
    // migration split it into are mapped back onto the same axis the comparator
    // already sorts by: `always` keeps the CORE floor, `criticality` supplies the
    // number underneath it (CRITICALITY_WEIGHTS). One chain, two grammars — a
    // consumer tiering by weight (the reflex battery) never computes its own.
    weight: contextPriority === 'always' ? Math.max(base, CORE_THRESHOLD) : base,
    // ── trigger fields (read by the reflex consumer, never rendered) ──────
    // v1 `use-when` prose survives migration as `retrieval.hint`; the
    // `use-when-pattern` precision glob as `retrieval.paths[0]`; the per-note
    // opt-out `reflex: off` as `retrieval.reflex`. They sit here, beside the
    // rest of the axis, so no consumer has to learn the v2 grammar twice.
    // ── visibility fields (read by isVisibleNow, never rendered) ──────────
    // Both grammars stamp validity time under the same two names (B5); the class
    // and the world are v2-only and simply read empty for a v1 note, which is
    // exactly «this record constrains nothing» — no v1 delivery moves.
    validFrom: renderableText(source.valid_from),
    validUntil: renderableText(source.valid_until),
    sensitivity: renderableText(source.sensitivity),
    scope: blockOf(source.scope),
    // ── trust fields (read by untrustedVerdict, never rendered) ───────────────
    // The body-derived signal, as TYPED FIELDS and nothing more: whether the body
    // could be read at all, and the NAMES of the markers that matched. The body is
    // not here and must never be — carrying it would put the payload on the axis
    // every consumer reads. A projection made without a scan (the consumers that
    // ask this module for an axis, not for a delivery decision) reads clean, which
    // is honest: nothing was scanned, so nothing is being claimed about it.
    bodyUnreadable: meta.bodyScan?.unreadable === true,
    injectionMarkers: Object.freeze([...(meta.bodyScan?.markers ?? [])]),
    hint: renderableText(source['use-when'] ?? retrieval.hint),
    pathPattern: renderableText(source['use-when-pattern'] ?? firstPath(retrieval)),
    reflexOptOut:
      renderableText(source.reflex ?? retrieval.reflex).toLowerCase() === 'off',
  }
}

/**
 * The v1 `kind` of a record, whichever grammar it is written in.
 *
 * v1 `kind` is a single word; v2 splits the same question across `memory_type`
 * (what sort of knowledge) and `truth_mode` (in what sense it is true). One v1
 * word collapsed onto a shared memory_type in that split — `bug-lesson` and
 * `procedural-rule` are BOTH `procedural` — so reading memory_type alone loses
 * the distinction that the corpus is asked for by name (the reflex consumer
 * asks for `bug-lesson`; nothing answers to `procedural`).
 *
 * The inverse is not a guess: migrate-v1-v2's KIND_TRANSFORM writes exactly
 * `bug-lesson -> procedural + factual` and `procedural-rule -> procedural +
 * normative`, so the pair reads back the word it came from. No new frontmatter
 * field, no data migration, one vocabulary. Every other memory_type is its own
 * answer and passes through untouched.
 */
const PROCEDURAL_BY_TRUTH_MODE = { factual: 'bug-lesson', normative: 'procedural-rule' }

function projectKind(fm) {
  const v1 = renderableText(fm.kind)
  if (v1) return v1
  const memoryType = renderableText(fm.memory_type)
  if (memoryType !== 'procedural') return memoryType
  const truthMode = renderableText(fm.truth_mode).toLowerCase()
  return PROCEDURAL_BY_TRUTH_MODE[truthMode] ?? memoryType
}

/** A frontmatter block as a plain object ({} when absent or malformed). */
function blockOf(v) {
  return v != null && typeof v === 'object' && !Array.isArray(v) ? v : {}
}

/** The v2 `retrieval` block as a plain object ({} when absent or malformed). */
function retrievalBlock(fm) {
  return blockOf(fm.retrieval)
}

/** The first entry of `retrieval.paths` (the migrated precision glob), or ''. */
function firstPath(retrieval) {
  const raw = retrieval.paths
  if (Array.isArray(raw)) return raw.length ? raw[0] : ''
  return raw ?? ''
}

/** A frontmatter value as trimmed text; anything absent renders as empty. */
function renderableText(v) {
  return v == null ? '' : String(v).trim()
}

/** v1 tags plus any v2 retrieval.areas not already among them, order preserved. */
function mergeAreas(fm) {
  const tags = Array.isArray(fm.tags) ? fm.tags : []
  const retrieval = fm.retrieval
  if (retrieval == null || typeof retrieval !== 'object' || Array.isArray(retrieval)) return tags
  const raw = retrieval.areas
  const areas = (Array.isArray(raw) ? raw : raw == null ? [] : [raw])
    .map((a) => String(a).trim())
    .filter((a) => a !== '')
  if (areas.length === 0) return tags
  return tags.concat(areas.filter((a) => !tags.includes(a)))
}

// ─────────────────────────── ordering (single truth) ─────────────────────────

/**
 * makeComparator(dateMap) — the ONE ordering key shared by the generator and the
 * loader (9-09): importance desc → injected last-commit date desc → name asc.
 * Recency is NEVER the primary filter (R4). A missing dateMap entry sorts last.
 *
 * Exported so loader.mjs can import a single ordering truth.
 *
 * @param {Record<string,string>} dateMap  file → last-commit ISO
 * @returns {(a:{file:string,importance:number}, b:{file:string,importance:number})=>number}
 */
export function makeComparator(dateMap = {}) {
  return (a, b) => {
    // `weight` is importance for a v1 note and the context_priority mapping for
    // a v2 record; a caller that builds note objects without it (the loader's
    // own shape) keeps the exact v1 behaviour through the fallback.
    const ia = a.weight ?? a.importance
    const ib = b.weight ?? b.importance
    if (ib !== ia) return ib - ia
    const da = dateMap[a.file] ?? EPOCH
    const db = dateMap[b.file] ?? EPOCH
    if (db !== da) return db < da ? -1 : 1 // date desc
    return a.file < b.file ? -1 : a.file > b.file ? 1 : 0 // name asc
  }
}

// ─────────────────────────── rendering ───────────────────────────────────────

/**
 * Max chars of a description rendered into one line (memory-hygiene C1: one line
 * per fact, under ~200 chars — the detail lives in the note file the line links to).
 * MEMORY.md is always-loaded context; unbounded descriptions ballooned it past the
 * harness partial-load limit (2026-07-03: 64 KB, only partially loaded).
 */
const LINE_DESC_MAX = 200

/** Truncate at the cap on a whole word, marking the cut with an ellipsis. */
function truncateClaim(s) {
  if (s.length <= LINE_DESC_MAX) return s
  const cut = s.slice(0, LINE_DESC_MAX - 1)
  const atWord = cut.replace(/\s+\S*$/, '')
  return `${(atWord.length >= LINE_DESC_MAX / 2 ? atWord : cut).trimEnd()}…`
}

/** Letters/digits only, lowercased — the corpus's echo use-whens drop punctuation. */
function normalizeForEcho(s) {
  return s.toLowerCase().replace(/[^\p{L}\p{N}]/gu, '')
}

/**
 * The bulk-migrated corpus auto-filled use-when as 'при работе с: <first words of
 * the description>' — a pure echo that doubled almost every index line. Render only
 * a use-when that carries its own signal; a genuine trigger ('перед пушем', 'в
 * начале любой сессии') never matches the echo shape and is kept.
 */
function renderableUseWhen(n) {
  if (!n.useWhen) return ''
  const m = n.useWhen.match(/^при работе с:\s*(.*)$/iu)
  if (m == null) return truncateClaim(n.useWhen)
  const probe = normalizeForEcho(m[1])
  if (probe === '' || normalizeForEcho(n.description).startsWith(probe)) return ''
  return truncateClaim(n.useWhen)
}

/**
 * CORE line: a standalone claim + its use-when (agents read this every load).
 * The claim is a markdown link `[desc](file)` so the note path is a real link that
 * the lint MEM-ORPHAN parser (which recognizes `](name.md)`) sees — CORE notes are
 * part of the index, not orphans. Bold-wrapped so CORE still reads as emphasized.
 */
function renderCoreLine(n) {
  const useWhen = renderableUseWhen(n)
  return `- **[${truncateClaim(n.description)}](${n.file})**${useWhen ? ` — ${useWhen}` : ''}${statusSuffix(n)}`
}

/**
 * The lifecycle marker on a rendered line. A record that is not `active` is
 * still findable, and a reader must be able to see WHY it reads oddly without
 * opening it. A v1 note carries no `status` at all, so this is empty for the
 * entire pre-schema-v2 corpus — the generated bytes do not move.
 */
function statusSuffix(n) {
  return n.status && n.status !== 'active' ? ` · status: ${n.status}` : ''
}
// trim.mjs sizes CORE demotions with the exact render the generator
// writes — exported so the byte math cannot drift from the artifact.
export { renderCoreLine }

/**
 * Index line (B10): a standalone claim + kind + tags + use-when + path, so an agent
 * judges relevance WITHOUT opening the file. One line per fact (C1).
 */
function renderIndexLine(n) {
  const tags = n.tags.join(', ')
  const useWhen = renderableUseWhen(n)
  return `- [${truncateClaim(n.description)}](${n.file}) · ${n.kind} · ${tags}${useWhen ? ` · ${useWhen}` : ''}${statusSuffix(n)}`
}

/** Order the CORE notes: kind subsection order, then the shared comparator within. */
function orderCore(coreNotes, cmp) {
  const rank = (k) => {
    const i = CORE_KIND_ORDER.indexOf(k)
    return i === -1 ? CORE_KIND_ORDER.length : i
  }
  return coreNotes.slice().sort((a, b) => {
    const ra = rank(a.kind)
    const rb = rank(b.kind)
    if (ra !== rb) return ra - rb
    return cmp(a, b)
  })
}

/**
 * buildIndex(opts) — render the whole MEMORY.md artifact deterministically.
 *
 * @param {object} opts
 * @param {string} opts.corpusDir      directory of the memory notes
 * @param {string} opts.tagsPath       path to TAGS.md (facet registry; parsed for stats)
 * @param {string} opts.commitHash     the build-anchor commit (INJECTED — never read here)
 * @param {Record<string,string>} [opts.dateMap]  file → last-commit ISO (INJECTED)
 * @param {number} [opts.coreThreshold]  importance at/above which a note is CORE
 * @returns {string}  the full generated MEMORY.md text (LF, no BOM)
 */
export function buildIndex(opts) {
  const {
    corpusDir,
    tagsPath,
    commitHash,
    dateMap = {},
    coreThreshold = CORE_THRESHOLD,
  } = opts

  const registry = loadTagsRegistry(tagsPath)

  const notes = readNotes(corpusDir)
  const cmp = makeComparator(dateMap)

  const core = orderCore(
    notes.filter((n) => isCoreNote(n, coreThreshold)),
    cmp,
  )
  // Everything CORE did not take — a demoted record is catalogued, never dropped.
  const periphery = notes.filter((n) => !isCoreNote(n, coreThreshold)).sort(cmp)
  const byArea = groupByArea(periphery, registry)

  const header = GENERATED_MARKER.replace('{commit}', commitHash ?? EPOCH)

  const out = []
  out.push(header)
  out.push('')
  out.push('# MEMORY — сгенерированный индекс памяти (R3)')
  out.push('')
  out.push(`> Построено из коммита \`${commitHash ?? EPOCH}\` · заметок: ${notes.length} · ядро: ${core.length} · индекс: ${periphery.length}.`)
  out.push('')

  // ── CORE (always loaded) ────────────────────────────────────────────────
  out.push('## Ядро (всегда загружается)')
  out.push('')
  if (core.length === 0) {
    out.push('_(пусто)_')
    out.push('')
  } else {
    for (const n of core) out.push(renderCoreLine(n))
    out.push('')
  }

  // ── Thin discovery layer (FI-11) ───────────────────────────────────────
  // One line per AREA with a count; the full one-line-per-note catalog lives
  // in the per-area INDEX-<area>.md files, pulled by tag on demand via
  // `node scripts/sma/cli.mjs load` — always-load stays within its byte budget with zero loss
  // of discoverability.
  out.push('## Обзор областей (полные индексы по требованию — `node scripts/sma/cli.mjs load --tags <area>`)')
  out.push('')
  if (byArea.size === 0) {
    out.push('_(пусто)_')
    out.push('')
  } else {
    for (const area of [...byArea.keys()].sort()) {
      const count = byArea.get(area).length
      out.push(`- ${area} — заметок: ${count} → [INDEX-${area}.md](INDEX-${area}.md)`)
    }
    out.push('')
  }

  // LF endings, trailing newline, no BOM.
  return out.join('\n')
}

// ─────────────────────────── per-area index files (FI-11) ────────────────────

/**
 * A note's discovery areas: its alias-resolved tags that are registered area
 * facets. A note with several area tags is catalogued in EVERY matching area
 * index (discoverability beats deduplication for a catalog); a note with no
 * registered area tag lands in the `misc` bucket so nothing is uncatalogued.
 */
function noteAreas(n, registry) {
  const resolved = (n.tags ?? []).map((t) => resolveAlias(String(t), registry))
  const areas = [...new Set(resolved.filter((t) => registry.area.has(t)))].sort()
  return areas.length ? areas : [MISC_AREA]
}

/** Group periphery notes into ordered area buckets (Map area → notes[]). */
function groupByArea(periphery, registry) {
  const byArea = new Map()
  for (const n of periphery) {
    for (const area of noteAreas(n, registry)) {
      if (!byArea.has(area)) byArea.set(area, [])
      byArea.get(area).push(n)
    }
  }
  return byArea
}

/**
 * buildAreaIndexes(opts) — render the per-area on-demand index files
 * (INDEX-<area>.md), each carrying the FULL one-line-per-note entries for its
 * area in the exact grammar of the old flat index (C1/B10). Deterministic like
 * buildIndex: commitHash + dateMap injected, LF endings, area-name-asc order.
 *
 * @param {object} opts  same contract as buildIndex
 * @returns {Array<{file:string, content:string}>}
 */
export function buildAreaIndexes(opts) {
  const {
    corpusDir,
    tagsPath,
    commitHash,
    dateMap = {},
    coreThreshold = CORE_THRESHOLD,
  } = opts

  const registry = loadTagsRegistry(tagsPath)
  const notes = readNotes(corpusDir)
  const cmp = makeComparator(dateMap)
  const periphery = notes.filter((n) => !isCoreNote(n, coreThreshold)).sort(cmp)
  const byArea = groupByArea(periphery, registry)

  const header = GENERATED_MARKER.replace('{commit}', commitHash ?? EPOCH)
  const out = []
  for (const area of [...byArea.keys()].sort()) {
    const lines = []
    lines.push(header)
    lines.push('')
    lines.push(`# INDEX — ${area} (по одной строке на факт)`)
    lines.push('')
    for (const n of byArea.get(area)) lines.push(renderIndexLine(n))
    lines.push('')
    out.push({ file: `INDEX-${area}.md`, content: lines.join('\n') })
  }
  return out
}

// ─────────────────────────── date map (injectable git) ───────────────────────

/**
 * computeDateMap({execGit}) — build a file → last-commit-ISO map from ONE git log
 * pass over the memory dir. The git runner is INJECTED (tests never shell out); in
 * production the CLI passes a runner that invokes:
 *   git log --format=%cI --name-only -- .claude/memory
 * The log is newest-commit-first, so the FIRST time a path is seen is its last
 * commit date. A path missing from the log has no map entry → the comparator's
 * epoch fallback sorts it last (documented; uncommitted files sort to the tail).
 *
 * @param {object} opts
 * @param {(args:string[])=>string} opts.execGit  read-only git runner
 * @param {string} [opts.memoryPathspec]  the pathspec passed to git log
 * @returns {Record<string,string>}  basename → last-commit ISO
 */
export function computeDateMap(opts) {
  const { execGit, memoryPathspec = '.claude/memory' } = opts
  const raw = execGit(['log', '--format=%cI', '--name-only', '--', memoryPathspec])
  const map = {}
  let currentDate = null
  for (const line of String(raw).split('\n')) {
    const trimmed = line.trim()
    if (trimmed === '') continue
    // An ISO-8601 line is a commit-date header; anything else is a file path.
    if (/^\d{4}-\d{2}-\d{2}T/.test(trimmed)) {
      currentDate = trimmed
      continue
    }
    if (currentDate == null) continue
    // Reduce to a basename so the map keys match the corpus file names.
    const base = trimmed.split('/').pop()
    if (!base || !base.endsWith('.md')) continue
    // First seen (newest commit) wins.
    if (!(base in map)) map[base] = currentDate
  }
  return map
}
